export const DISTRICTS = [
  { slug: "chennai", name_en: "Chennai", name_ta: "சென்னை", region: "north" },
  { slug: "coimbatore", name_en: "Coimbatore", name_ta: "கோயம்புத்தூர்", region: "west" },
  { slug: "madurai", name_en: "Madurai", name_ta: "மதுரை", region: "south" },
  { slug: "tiruchirappalli", name_en: "Tiruchirappalli", name_ta: "திருச்சிராப்பள்ளி", region: "central" },
  { slug: "salem", name_en: "Salem", name_ta: "சேலம்", region: "north" },
  { slug: "tirunelveli", name_en: "Tirunelveli", name_ta: "திருநெல்வேலி", region: "south" },
  { slug: "vellore", name_en: "Vellore", name_ta: "வேலூர்", region: "north" },
  { slug: "erode", name_en: "Erode", name_ta: "ஈரோடு", region: "west" },
  { slug: "thoothukudi", name_en: "Thoothukudi", name_ta: "தூத்துக்குடி", region: "south" },
  { slug: "dindigul", name_en: "Dindigul", name_ta: "டிண்டுக்கல்", region: "south" },
  { slug: "thanjavur", name_en: "Thanjavur", name_ta: "தஞ்சாவூர்", region: "central" },
  { slug: "ranipet", name_en: "Ranipet", name_ta: "ராணிப்பேட்டை", region: "north" },
  { slug: "sivaganga", name_en: "Sivaganga", name_ta: "சிவகங்கை", region: "south" },
  { slug: "virudhunagar", name_en: "Virudhunagar", name_ta: "விருதுநகர்", region: "south" },
  { slug: "nagapattinam", name_en: "Nagapattinam", name_ta: "நாகப்பட்டினம்", region: "central" },
  { slug: "kallakurichi", name_en: "Kallakurichi", name_ta: "கள்ளக்குறிச்சி", region: "north" },
  { slug: "chengalpattu", name_en: "Chengalpattu", name_ta: "செங்கல்பட்டு", region: "north" },
  { slug: "tiruppur", name_en: "Tiruppur", name_ta: "திருப்பூர்", region: "west" },
  { slug: "tenkasi", name_en: "Tenkasi", name_ta: "தென்காசி", region: "south" },
  { slug: "mayiladuthurai", name_en: "Mayiladuthurai", name_ta: "மயிலாடுதுறை", region: "central" },
  { slug: "tirupattur", name_en: "Tirupattur", name_ta: "திருப்பத்தூர்", region: "north" },
  { slug: "nilgiris", name_en: "The Nilgiris", name_ta: "நீலகிரி", region: "west" },
  { slug: "krishnagiri", name_en: "Krishnagiri", name_ta: "கிருஷ்ணகிரி", region: "north" },
  { slug: "dharmapuri", name_en: "Dharmapuri", name_ta: "தர்மபுரி", region: "north" },
  { slug: "cuddalore", name_en: "Cuddalore", name_ta: "கடலூர்", region: "central" },
  { slug: "villupuram", name_en: "Villupuram", name_ta: "விழுப்புரம்", region: "central" },
  { slug: "perambalur", name_en: "Perambalur", name_ta: "பெரம்பலூர்", region: "central" },
  { slug: "ariyalur", name_en: "Ariyalur", name_ta: "அரியலூர்", region: "central" },
  { slug: "pudukkottai", name_en: "Pudukkottai", name_ta: "புதுக்கோட்டை", region: "central" },
  { slug: "ramanathapuram", name_en: "Ramanathapuram", name_ta: "ராமநாதபுரம்", region: "south" },
  { slug: "theni", name_en: "Theni", name_ta: "தேனி", region: "south" },
  { slug: "kancheepuram", name_en: "Kancheepuram", name_ta: "காஞ்சிபுரம்", region: "north" },
  { slug: "tiruvarur", name_en: "Tiruvarur", name_ta: "திருவாரூர்", region: "central" },
  { slug: "karur", name_en: "Karur", name_ta: "கரூர்", region: "central" },
  { slug: "namakkal", name_en: "Namakkal", name_ta: "நாமக்கல்", region: "west" },
  { slug: "tiruvannamalai", name_en: "Tiruvannamalai", name_ta: "திருவண்ணாமலை", region: "north" },
  { slug: "kanyakumari", name_en: "Kanyakumari", name_ta: "கன்னியாகுமரி", region: "south" },
  { slug: "tiruvallur", name_en: "Tiruvallur", name_ta: "திருவள்ளூர்", region: "north" }
];

export const getDistrictBySlug = (slug) =>
  DISTRICTS.find((d) => d.slug === slug) || null;