// 17th Tamil Nadu Legislative Assembly (2026-2031)
// Official Representative Ledger across all 38 Districts of Tamil Nadu

export const TN_MLAS_DATA = [
  {
    "district_slug": "chennai",
    "district_name": "Chennai",
    "district_name_ta": "சென்னை",
    "mla_name": "C. Joseph Vijay",
    "mla_name_ta": "சி. ஜோசப் விஜய்",
    "party_slug": "tvk",
    "party_name": "TVK",
    "constituency": "Kolathur (013)",
    "constituency_ta": "கொளத்தூர் (013)",
    "photo_url": "https://upload.wikimedia.org/wikipedia/commons/0/06/C._Joseph_Vijay_%28cropped%29.jpg",
    "elected_date": "2026-05-04",
    "vote_share": 52.4,
    "winning_margin": 28410,
    "performance_score": 91,
    "key_actions_en": "Chief Minister of Tamil Nadu (Sworn in May 10, 2026).\nKamarajar Breakfast Scheme expanded to 15,454 schools across Tamil Nadu.\nWhite paper disclosure on ₹10 lakh crore state public debt.\nDirect citizen grievance cell \"Makkalodu Vijay\" inaugurated.",
    "key_actions_ta": "தமிழ்நாடு முதலமைச்சர் (பதவியேற்பு: மே 10, 2026).\n15,454 பள்ளிகளில் காமராஜர் காலை உணவுத் திட்டம் விரிவாக்கம்.\nமாநிலத்தின் ₹10 லட்சம் கோடி கடன் குறித்த வெள்ளை அறிக்கை வெளியீடு.\n\"மக்களோடு விஜய்\" மக்கள் குறைதீர்ப்பு மையம் தொடக்கம்.",
    "is_active": true
  },
  {
    "district_slug": "salem",
    "district_name": "Salem",
    "district_name_ta": "சேலம்",
    "mla_name": "Edappadi K. Palaniswami",
    "mla_name_ta": "எடப்பாடி கே. பழனிசாமி",
    "party_slug": "aiadmk",
    "party_name": "AIADMK",
    "constituency": "Edappadi (086)",
    "constituency_ta": "எடப்பாடி (086)",
    "photo_url": "https://upload.wikimedia.org/wikipedia/commons/f/f7/K._Palaniswami.jpg",
    "elected_date": "2026-05-04",
    "vote_share": 62.15,
    "winning_margin": 68420,
    "performance_score": 87,
    "key_actions_en": "Leader of Opposition in 17th Tamil Nadu Legislative Assembly.\nChallenged state budget allocations and raised power cut issues.\nField mobilization across Western Tamil Nadu districts.",
    "key_actions_ta": "17வது தமிழ்நாடு சட்டமன்ற எதிர்க்கட்சித் தலைவர்.\nசட்டசபையில் மின்தடை மற்றும் பட்ஜெட் ஒதுக்கீடு குறித்த கேள்விகள் எழுப்புதல்.\nமேற்கு மாவட்டங்களில் அதிமுக கட்டமைப்பு மறுசீரமைப்பு.",
    "is_active": true
  },
  {
    "district_slug": "coimbatore",
    "district_name": "Coimbatore",
    "district_name_ta": "கோயம்புத்தூர்",
    "mla_name": "Vanathi Srinivasan",
    "mla_name_ta": "வானதி சீனிவாசன்",
    "party_slug": "bjp",
    "party_name": "BJP",
    "constituency": "Coimbatore South (120)",
    "constituency_ta": "கோயம்புத்தூர் தெற்கு (120)",
    "photo_url": "https://upload.wikimedia.org/wikipedia/commons/c/c5/Vanathi_Srinivasan_in_2021.jpg",
    "elected_date": "2026-05-04",
    "vote_share": 36.8,
    "winning_margin": 3120,
    "performance_score": 82,
    "key_actions_en": "Representation to Union Defense Ministry for Coimbatore Defense Innovation Hub.\nAirport runway expansion land acquisition coordination.\nMSME electricity tariff subsidy advocacy on the assembly floor.",
    "key_actions_ta": "கோவை பாதுகாப்பு தொழில் மையம் அமைய மத்திய அமைச்சகத்திடம் மனு.\nவிமான நிலைய விரிவாக்க நில எடுப்பு பணிகள் மேற்பார்வை.\nசிறு-குறு தொழில் மின் கட்டண சலுகை குறித்த சட்டமன்ற கோரிக்கை.",
    "is_active": true
  },
  {
    "district_slug": "madurai",
    "district_name": "Madurai",
    "district_name_ta": "மதுரை",
    "mla_name": "Dr. Palanivel Thiagarajan",
    "mla_name_ta": "முனைவர் பழனிவேல் தியாகராஜன்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Madurai Central (191)",
    "constituency_ta": "மதுரை மத்தியம் (191)",
    "photo_url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d1/Palanivel_Thiaga_Rajan%2C_Minister_for_Information_Technology_%26_Digital_Services%2C_Government_of_Tamil_Nadu%2C_keynoting_the_Horasis_India_Meeting_%28Cropped%29.jpg/500px-Palanivel_Thiaga_Rajan%2C_Minister_for_Information_Technology_%26_Digital_Services%2C_Government_of_Tamil_Nadu%2C_keynoting_the_Horasis_India_Meeting_%28Cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "elected_date": "2026-05-04",
    "vote_share": 51.1,
    "winning_margin": 18450,
    "performance_score": 89,
    "key_actions_en": "Senior opposition spokesperson on fiscal policy and data governance.\nMonitoring Madurai Metro DPR progress.\nKalaignar Memorial Library digital expansion and civil service coaching.",
    "key_actions_ta": "நிதி கொள்கை மற்றும் தகவல் தொழில்நுட்பம் குறித்த எதிர்க்கட்சி முதன்மை குரல்.\nமதுரை மெட்ரோ திட்டப் பணிகள் தொடர் கண்காணிப்பு.\nகலைஞர் நூற்றாண்டு நூலக டிஜிட்டல் விரிவாக்கம்.",
    "is_active": true
  },
  {
    "district_slug": "erode",
    "district_name": "Erode",
    "district_name_ta": "ஈரோடு",
    "mla_name": "K. A. Sengottaiyan",
    "mla_name_ta": "கே. ஏ. செங்கோட்டையன்",
    "party_slug": "tvk",
    "party_name": "TVK",
    "constituency": "Gobichettipalayam (106)",
    "constituency_ta": "கோபிசெட்டிபாளையம் (106)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 54.3,
    "winning_margin": 24890,
    "performance_score": 88,
    "key_actions_en": "Senior Cabinet Minister for Finance in TVK alliance administration.\nDrafting Tamil Nadu Debt Restructuring and Fiscal Responsibility white paper.\nKalingarayan canal modernization and textile zero-liquid discharge subsidies.",
    "key_actions_ta": "தமிழக வெற்றிக் கழக கூட்டணி அரசின் நிதித்துறை அமைச்சர்.\nமாநில கடன் மறுசீரமைப்பு மற்றும் நிதி மேலாண்மை அறிக்கை தயாரிப்பு.\nகாலிங்கராயன் வாய்க்கால் சீரமைப்பு மற்றும் சாய ஆலை சுத்திகரிப்பு மானியம்.",
    "is_active": true
  },
  {
    "district_slug": "tiruchirappalli",
    "district_name": "Tiruchirappalli",
    "district_name_ta": "திருச்சிராப்பள்ளி",
    "mla_name": "K. N. Nehru",
    "mla_name_ta": "கே. என். நேரு",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Tiruchirappalli West (140)",
    "constituency_ta": "திருச்சிராப்பள்ளி மேற்கு (140)",
    "photo_url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/11/Nehru_in_an_public_meeting.jpg/500px-Nehru_in_an_public_meeting.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "elected_date": "2026-05-04",
    "vote_share": 49.8,
    "winning_margin": 12400,
    "performance_score": 85,
    "key_actions_en": "Senior DMK leader reviewing Cauvery delta flood defenses.\nPanjapur integrated bus terminus operations follow-up.\nAssembly questions on civic fund allocation to non-ruling constituencies.",
    "key_actions_ta": "காவிரி டெல்டா வெள்ளத் தடுப்பு பணிகள் ஆய்வு.\nபஞ்சப்பூர் ஒருங்கிணைந்த பேருந்து நிலைய செயல்பாடுகள் கண்காணிப்பு.\nசட்டசபையில் திருச்சி மாநகர வளர்ச்சி நிதி குறித்த கேள்விகள்.",
    "is_active": true
  },
  {
    "district_slug": "villupuram",
    "district_name": "Villupuram",
    "district_name_ta": "விழுப்புரம்",
    "mla_name": "N. Anand (Bussy Anand)",
    "mla_name_ta": "என். ஆனந்த் (புஸ்ஸி ஆனந்த்)",
    "party_slug": "tvk",
    "party_name": "TVK",
    "constituency": "Vikravandi (075)",
    "constituency_ta": "விக்கிரவாண்டி (075)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 58.7,
    "winning_margin": 41200,
    "performance_score": 87,
    "key_actions_en": "TVK General Secretary representing the party historic Vikravandi conference base.\nVikravandi agro-industrial hub and cold chain network development.\nGround-level grievance resolution camps across Villupuram district.",
    "key_actions_ta": "தவெக பொதுச்செயலாளர், விக்கிரவாண்டி வரலாற்று மாநாட்டு தொகுதி பிரதிநிதி.\nவிக்கிரவாண்டி வேளாண் தொழில் மையம் மற்றும் குளிர்பதன கிடங்கு அமைத்தல்.\nவிழுப்புரம் மாவட்டம் முழுவதும் கள அளவிலான மக்கள் குறைதீர்ப்பு முகாம்கள்.",
    "is_active": true
  },
  {
    "district_slug": "chengalpattu",
    "district_name": "Chengalpattu",
    "district_name_ta": "செங்கல்பட்டு",
    "mla_name": "C. Mahendran",
    "mla_name_ta": "சி. மகேந்திரன்",
    "party_slug": "tvk",
    "party_name": "TVK",
    "constituency": "Tambaram (031)",
    "constituency_ta": "தாம்பரம் (031)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 48.9,
    "winning_margin": 14210,
    "performance_score": 84,
    "key_actions_en": "Tambaram flood defense coordination and stormwater drain integration.\nGST road elevated flyover decongestion review.\nSouth suburban drinking water pipeline connections.",
    "key_actions_ta": "தாம்பரம் மழைநீர் வடிகால் மற்றும் வெள்ளத் தடுப்பு ஒருங்கிணைப்பு.\nஜிஎஸ்டி சாலை போக்குவரத்து நெரிசல் தீர்வு ஆய்வு.\nதென் புறநகர் குடிநீர் குழாய் திட்டப் பணிகள்.",
    "is_active": true
  },
  {
    "district_slug": "tiruvallur",
    "district_name": "Tiruvallur",
    "district_name_ta": "திருவள்ளூர்",
    "mla_name": "B. Venkatraman",
    "mla_name_ta": "பி. வெங்கட்ராமன்",
    "party_slug": "tvk",
    "party_name": "TVK",
    "constituency": "Avadi (006)",
    "constituency_ta": "ஆவடி (006)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 47.6,
    "winning_margin": 11800,
    "performance_score": 83,
    "key_actions_en": "Avadi Lake rejuvenation and ecopark project.\nHeavy Vehicles Factory (HVF) local youth contract labor representations.\nTiruvallur district hospital infrastructure enhancement.",
    "key_actions_ta": "ஆவடி ஏரி புனரமைப்பு மற்றும் சூழல் பூங்கா அமைக்கும் பணி.\nஉள்ளூர் இளைஞர்களுக்கு தொழிற்பேட்டை வேலைவாய்ப்பு கோரிக்கை.\nதிருவள்ளூர் மாவட்ட தலைமை மருத்துவமனை வசதிகள் மேம்பாடு.",
    "is_active": true
  },
  {
    "district_slug": "kancheepuram",
    "district_name": "Kancheepuram",
    "district_name_ta": "காஞ்சிபுரம்",
    "mla_name": "Dr. K. Santhosh",
    "mla_name_ta": "மருத்துவர் கே. சந்தோஷ்",
    "party_slug": "tvk",
    "party_name": "TVK",
    "constituency": "Kancheepuram (037)",
    "constituency_ta": "காஞ்சிபுரம் (037)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 46.8,
    "winning_margin": 9400,
    "performance_score": 82,
    "key_actions_en": "Silk weavers raw material subsidy distribution.\nVegavathi river desilting and temple city bypass road work.\nHandloom cluster export support centers.",
    "key_actions_ta": "பட்டு நெசவாளர்களுக்கு மானிய விலை கச்சா பட்டு விநியோகம்.\nவேகவதி நதி தூர்வாருதல் மற்றும் கோயில் நகர புறவழிச்சாலை.\nகைத்தறி ஜவுளி ஏற்றுமதி மையம்.",
    "is_active": true
  },
  {
    "district_slug": "vellore",
    "district_name": "Vellore",
    "district_name_ta": "வேலூர்",
    "mla_name": "Duraimurugan",
    "mla_name_ta": "துரைமுருகன்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Katpadi (040)",
    "constituency_ta": "காட்பாடி (040)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 50.2,
    "winning_margin": 6200,
    "performance_score": 86,
    "key_actions_en": "Senior DMK veteran and legislative mentor.\nPalar river groundwater protection and check dam oversight.\nVellore Abdullapuram airport connectivity follow-ups.",
    "key_actions_ta": "சட்டமன்ற மூத்த தலைவர், திமுக வழிகாட்டி.\nபாலாறு தடுப்பணைகள் மற்றும் நிலத்தடி நீர் பாதுகாப்பு.\nவேலூர் விமான நிலைய சாலை இணைப்பு பணிகள்.",
    "is_active": true
  },
  {
    "district_slug": "ranipet",
    "district_name": "Ranipet",
    "district_name_ta": "ராணிப்பேட்டை",
    "mla_name": "R. Gandhi",
    "mla_name_ta": "ஆர். காந்தி",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Ranipet (041)",
    "constituency_ta": "ராணிப்பேட்டை (041)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 45.9,
    "winning_margin": 4800,
    "performance_score": 81,
    "key_actions_en": "SIPCOT leather industrial effluent modernization advocacy.\nRanipet District collectorate campus amenities review.\nPalar check dam water recharge initiatives.",
    "key_actions_ta": "சிப்காட் தோல் பதனிடும் ஆலை கழிவுநீர் சுத்திகரிப்பு கோரிக்கைகள்.\nராணிப்பேட்டை மாவட்ட ஆட்சியர் அலுவலக மக்கள் வசதிகள்.\nபாலாறு தடுப்பணை பராமரிப்பு பணிகள்.",
    "is_active": true
  },
  {
    "district_slug": "tirupattur",
    "district_name": "Tirupattur",
    "district_name_ta": "திருப்பத்தூர்",
    "mla_name": "A. C. Shanmugam",
    "mla_name_ta": "ஏ. சி. சண்முகம்",
    "party_slug": "tvk",
    "party_name": "TVK",
    "constituency": "Vaniyambadi (048)",
    "constituency_ta": "வாணியம்பாடி (048)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 48.3,
    "winning_margin": 8600,
    "performance_score": 83,
    "key_actions_en": "Leather goods cluster export incentive representation.\nYelagiri hills eco-tourism road widening.\nVaniyambadi municipal water supply enhancement.",
    "key_actions_ta": "தோல் காலணி உற்பத்தி ஏற்றுமதி சலுகைகள்.\nஏலகிரி மலை சுற்றுலா சாலை விரிவாக்கம்.\nவாணியம்பாடி நகராட்சி குடிநீர் விநியோக சீரமைப்பு.",
    "is_active": true
  },
  {
    "district_slug": "dharmapuri",
    "district_name": "Dharmapuri",
    "district_name_ta": "தர்மபுரி",
    "mla_name": "S. P. Venkateshwaran",
    "mla_name_ta": "எஸ். பி. வெங்கடேஸ்வரன்",
    "party_slug": "pmk",
    "party_name": "PMK",
    "constituency": "Dharmapuri (084)",
    "constituency_ta": "தர்மபுரி (084)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 47.9,
    "winning_margin": 14300,
    "performance_score": 82,
    "key_actions_en": "Cauvery-Surplus water irrigation scheme advocacy.\nMorappur-Dharmapuri railway line execution representations.\nMango processing food park establishment.",
    "key_actions_ta": "காவிரி உபரி நீர் பாசன திட்ட கோரிக்கைகள்.\nமொரப்பூர் - தர்மபுரி ரயில்வே இணைப்பு பணிகள்.\nமாம்பழ பதப்படுத்தும் உணவு பூங்கா அமைத்தல்.",
    "is_active": true
  },
  {
    "district_slug": "krishnagiri",
    "district_name": "Krishnagiri",
    "district_name_ta": "கிருஷ்ணகிரி",
    "mla_name": "K. Ashok Kumar",
    "mla_name_ta": "கே. அசோக் குமார்",
    "party_slug": "aiadmk",
    "party_name": "AIADMK",
    "constituency": "Krishnagiri (053)",
    "constituency_ta": "கிருஷ்ணகிரி (053)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 48.1,
    "winning_margin": 9200,
    "performance_score": 80,
    "key_actions_en": "Hosur industrial belt infrastructure demands in Assembly.\nKelavarapalli dam water quality follow-up.\nNational highway traffic bottleneck clearances.",
    "key_actions_ta": "ஓசூர் தொழிற்பேட்டை அடிப்படை வசதிகள் குறித்த சட்டமன்ற குரல்.\nகெலவரப்பள்ளி அணை நீர் சுத்திகரிப்பு ஆய்வு.\nதேசிய நெடுஞ்சாலை போக்குவரத்து நெரிசல் தீர்வு.",
    "is_active": true
  },
  {
    "district_slug": "namakkal",
    "district_name": "Namakkal",
    "district_name_ta": "நாமக்கல்",
    "mla_name": "S. Suriyamoorthy",
    "mla_name_ta": "எஸ். சூரியமூர்த்தி",
    "party_slug": "tvk",
    "party_name": "TVK",
    "constituency": "Namakkal (095)",
    "constituency_ta": "நாமக்கல் (095)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 49.2,
    "winning_margin": 11400,
    "performance_score": 82,
    "key_actions_en": "Poultry industry feed maize subsidy representations.\nLorry transport body building cluster infrastructure.\nMohanur railway overbridge execution push.",
    "key_actions_ta": "கோழிப்பண்ணை தொழிலுக்கு மக்காச்சோள தீவன மானியம்.\nலாரி கூண்டு கட்டும் தொழிற்பேட்டை வசதிகள்.\nமோகனூர் ரயில்வே மேம்பால பணிகள்.",
    "is_active": true
  },
  {
    "district_slug": "nilgiris",
    "district_name": "Nilgiris",
    "district_name_ta": "நீலகிரி",
    "mla_name": "R. Ganesh",
    "mla_name_ta": "ஆர். கணேஷ்",
    "party_slug": "inc",
    "party_name": "INC",
    "constituency": "Udhagamandalam (108)",
    "constituency_ta": "உதகமண்டலம் (108)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 45.4,
    "winning_margin": 3800,
    "performance_score": 80,
    "key_actions_en": "Tea estate worker minimum wage revision advocacy.\nWildlife corridor human-animal conflict control rapid squads.\nNilgiri Mountain Railway heritage infrastructure protection.",
    "key_actions_ta": "தேயிலைத் தோட்டத் தொழிலாளர்கள் ஊதிய உயர்வு கோரிக்கை.\nமனித-விலங்கு மோதல் தடுப்பு அதிவிரைவுப் படைகள்.\nநீலகிரி மலை ரயில் பாரம்பரிய பாதை பராமரிப்பு.",
    "is_active": true
  },
  {
    "district_slug": "tiruppur",
    "district_name": "Tiruppur",
    "district_name_ta": "திருப்பூர்",
    "mla_name": "M. S. M. Anandan",
    "mla_name_ta": "எம். எஸ். எம். ஆனந்தன்",
    "party_slug": "aiadmk",
    "party_name": "AIADMK",
    "constituency": "Tiruppur North (113)",
    "constituency_ta": "திருப்பூர் வடக்கு (113)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 47.3,
    "winning_margin": 7100,
    "performance_score": 81,
    "key_actions_en": "Knitwear export cluster raw material price stabilisation petition.\nNoyyal river cleanup and CETP power subsidy representation.\nTiruppur city outer ring road follow-up.",
    "key_actions_ta": "பின்னலாடை உற்பத்தி மூலப்பொருள் விலை நிலைத்தன்மை கோரிக்கை.\nநொய்யல் நதி புனரமைப்பு மற்றும் சுத்திகரிப்பு ஆலை மின் மானியம்.\nதிருப்பூர் வெளிவட்டச் சாலை பணிகள்.",
    "is_active": true
  },
  {
    "district_slug": "karur",
    "district_name": "Karur",
    "district_name_ta": "கரூர்",
    "mla_name": "V. Senthilbalaji",
    "mla_name_ta": "வி. செந்தில்பாலாஜி",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Karur (135)",
    "constituency_ta": "கரூர் (135)",
    "photo_url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/84/Senthil_Balaji_Official_Potrait.png/500px-Senthil_Balaji_Official_Potrait.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "elected_date": "2026-05-04",
    "vote_share": 51.4,
    "winning_margin": 16200,
    "performance_score": 86,
    "key_actions_en": "Senior DMK strategist and Western TN floor coordinator.\nMayanur barrage irrigation canal works review.\nKarur home textile export cluster logistics representations.",
    "key_actions_ta": "சட்டசபையில் திமுக மேற்கு மண்டல ஒருங்கிணைப்பு.\nமாயனூர் கதவணை பாசன வாய்க்கால் பராமரிப்பு.\nகரூர் வீட்டு உபயோக ஜவுளி ஏற்றுமதி வசதிகள்.",
    "is_active": true
  },
  {
    "district_slug": "dindigul",
    "district_name": "Dindigul",
    "district_name_ta": "திண்டுக்கல்",
    "mla_name": "Dindigul C. Sreenivasan",
    "mla_name_ta": "திண்டுக்கல் சி. சீனிவாசன்",
    "party_slug": "aiadmk",
    "party_name": "AIADMK",
    "constituency": "Dindigul (127)",
    "constituency_ta": "திண்டுக்கல் (127)",
    "photo_url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/14/C._Sreenivasan.jpg/500px-C._Sreenivasan.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "elected_date": "2026-05-04",
    "vote_share": 49.1,
    "winning_margin": 11900,
    "performance_score": 81,
    "key_actions_en": "Lock and brass metal craft worker welfare representations.\nAthoor dam drinking water scheme maintenance.\nSirumalai horticultural produce direct procurement.",
    "key_actions_ta": "பூட்டு மற்றும் பித்தளை கைவினைஞர்கள் நலவாரிய உதவிகள்.\nஆத்தூர் அணை குடிநீர் விநியோக சீரமைப்பு.\nசிறுமலை காய்கறி விவசாயிகள் நேரடி விற்பனை மையம்.",
    "is_active": true
  },
  {
    "district_slug": "theni",
    "district_name": "Theni",
    "district_name_ta": "தேனி",
    "mla_name": "O. Panneerselvam",
    "mla_name_ta": "ஓ. பன்னீர்செல்வம்",
    "party_slug": "independent",
    "party_name": "Independent",
    "constituency": "Bodinayakanur (199)",
    "constituency_ta": "போடிநாயக்கனூர் (199)",
    "photo_url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0a/O._Panneerselvam.jpg/500px-O._Panneerselvam.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "elected_date": "2026-05-04",
    "vote_share": 48.7,
    "winning_margin": 13200,
    "performance_score": 82,
    "key_actions_en": "Former Chief Minister advocating for Mullaperiyar dam safety and rights.\nCardamom and spice grower transportation subsidy representations.\n18th canal irrigation water release schedule monitoring.",
    "key_actions_ta": "முல்லைப்பெரியாறு அணை உரிமை மற்றும் பாதுகாப்பு குரல்.\nஏலக்காய் விவசாயிகள் போக்குவரத்து மானிய கோரிக்கைகள்.\n18-ம் கால்வாய் பாசன நீர் திறப்பு கண்காணிப்பு.",
    "is_active": true
  },
  {
    "district_slug": "virudhunagar",
    "district_name": "Virudhunagar",
    "district_name_ta": "விருதுநகர்",
    "mla_name": "Thangam Thennarasu",
    "mla_name_ta": "தங்கம் தென்னரசு",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Tiruchuli (208)",
    "constituency_ta": "திருச்சுழி (208)",
    "photo_url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5a/Thangam_Thennarasu.jpg/500px-Thangam_Thennarasu.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "elected_date": "2026-05-04",
    "vote_share": 55.6,
    "winning_margin": 31200,
    "performance_score": 90,
    "key_actions_en": "Senior DMK economic strategist scrutinising TVK government fiscal policy.\nPM MITRA mega textile park execution follow-up in Virudhunagar.\nKariapatti drinking water supply scheme review.",
    "key_actions_ta": "சட்டமன்றத்தில் நிதி மற்றும் பொருளாதார விவகாரங்கள் குறித்த திமுக முதன்மை பேச்சாளர்.\nவிருதுநகர் பிஎம் மித்ரா மெகா ஜவுளி பூங்கா பணிகள் கண்காணிப்பு.\nகாரியாபட்டி கூட்டுக் குடிநீர் திட்டம் ஆய்வு.",
    "is_active": true
  },
  {
    "district_slug": "sivaganga",
    "district_name": "Sivaganga",
    "district_name_ta": "சிவகங்கை",
    "mla_name": "P. R. Senthilnathan",
    "mla_name_ta": "பி. ஆர். செந்தில்நாதன்",
    "party_slug": "aiadmk",
    "party_name": "AIADMK",
    "constituency": "Sivaganga (184)",
    "constituency_ta": "சிவகங்கை (184)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 46.2,
    "winning_margin": 5400,
    "performance_score": 79,
    "key_actions_en": "Keeladi museum road link improvements.\nVaigai surplus water supply for drought-hit tanks in Sivaganga.\nDistrict government hospital trauma care unit demands.",
    "key_actions_ta": "கீழடி அருங்காட்சியக சாலை இணைப்பு வசதிகள்.\nவைகை உபரி நீர் சிவகங்கை கண்மாய்களுக்கு திருப்பி விடக் கோரிக்கை.\nமாவட்ட அரசு மருத்துவமனை அவசர சிகிச்சை பிரிவு மேம்பாடு.",
    "is_active": true
  },
  {
    "district_slug": "ramanathapuram",
    "district_name": "Ramanathapuram",
    "district_name_ta": "இராமநாதபுரம்",
    "mla_name": "Katharbatcha Muthuramalingam",
    "mla_name_ta": "காதர்பாட்ஷா முத்துராமலிங்கம்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Ramanathapuram (211)",
    "constituency_ta": "இராமநாதபுரம் (211)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 48.9,
    "winning_margin": 14800,
    "performance_score": 81,
    "key_actions_en": "Seawater desalination drinking water scheme expansion.\nRamanathapuram chili farmers export cold storage hub.\nRameshwaram pilgrimage road and sanitation infrastructure.",
    "key_actions_ta": "கடல்நீரை குடிநீராக்கும் திட்ட விரிவாக்கம்.\nராமநாதபுரம் குண்டு மிளகாய் விவசாயிகளுக்கு குளிர்பதன கிடங்கு.\nராமேஸ்வரம் புனித யாத்திரை சாலை மற்றும் சுகாதார வசதிகள்.",
    "is_active": true
  },
  {
    "district_slug": "thoothukudi",
    "district_name": "Thoothukudi",
    "district_name_ta": "தூத்துக்குடி",
    "mla_name": "P. Geetha Jeevan",
    "mla_name_ta": "பி. கீதா ஜீவன்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Thoothukudi (215)",
    "constituency_ta": "தூத்துக்குடி (215)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 49.3,
    "winning_margin": 11200,
    "performance_score": 83,
    "key_actions_en": "Stormwater pump station maintenance across Thoothukudi Corporation.\nSalt pan worker monsoon welfare compensation follow-up.\nV.O.C. Port industrial corridor employment generation.",
    "key_actions_ta": "தூத்துக்குடி மாநகராட்சி மழைநீர் வடிகால் நிலையங்கள் கண்காணிப்பு.\nஉப்பளத் தொழிலாளர்களுக்கு மழைக்கால நிவாரண உதவி.\nவ.உ.சி துறைமுக தொழிற்பேட்டை வேலைவாய்ப்பு முகாம்கள்.",
    "is_active": true
  },
  {
    "district_slug": "tirunelveli",
    "district_name": "Tirunelveli",
    "district_name_ta": "திருநெல்வேலி",
    "mla_name": "Nainar Nagendran",
    "mla_name_ta": "நயினார் நாகேந்திரன்",
    "party_slug": "bjp",
    "party_name": "BJP",
    "constituency": "Tirunelveli (224)",
    "constituency_ta": "திருநெல்வேலி (224)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 45.8,
    "winning_margin": 8900,
    "performance_score": 82,
    "key_actions_en": "Thamirabarani river sewage prevention and desilting project.\nTirunelveli Junction railway terminal platform upgrades.\nPalm jaggery cooperative grievance representations.",
    "key_actions_ta": "தாமிரபரணி நதி கழிவுநீர் கலப்பு தடுப்பு பணிகள்.\nதிருநெல்வேலி சந்திப்பு ரயில் நிலைய கூடுதல் முனையப் பணிகள்.\nபனை விவசாயிகளுக்கான உதவித்திட்ட நடவடிக்கைகள்.",
    "is_active": true
  },
  {
    "district_slug": "tenkasi",
    "district_name": "Tenkasi",
    "district_name_ta": "தென்காசி",
    "mla_name": "S. Palani Nadar",
    "mla_name_ta": "எஸ். பழனி நாடார்",
    "party_slug": "inc",
    "party_name": "INC",
    "constituency": "Tenkasi (222)",
    "constituency_ta": "தென்காசி (222)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 43.1,
    "winning_margin": 1900,
    "performance_score": 80,
    "key_actions_en": "Courtallam waterfalls tourist amenities and safety renovations.\nTenkasi-Tirunelveli railway electrification.\nHorticulture lemon and mango farmers marketing support.",
    "key_actions_ta": "குற்றால அருவிகள் சுற்றுலா பயணிகள் பாதுகாப்பு மேம்பாடு.\nதென்காசி - நெல்லை ரயில் மின்மயமாக்கல்.\nஎலுமிச்சை மற்றும் மாம்பழ விவசாயிகளுக்கு நேரடி விற்பனை மையம்.",
    "is_active": true
  },
  {
    "district_slug": "kanniyakumari",
    "district_name": "Kanniyakumari",
    "district_name_ta": "கன்னியாகுமரி",
    "mla_name": "M. R. Gandhi",
    "mla_name_ta": "எம். ஆர். காந்தி",
    "party_slug": "bjp",
    "party_name": "BJP",
    "constituency": "Nagercoil (230)",
    "constituency_ta": "நாகர்கோவில் (230)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 47.1,
    "winning_margin": 8400,
    "performance_score": 80,
    "key_actions_en": "Four-lane highway works connecting Nagercoil to Trivandrum.\nRubber and coconut MSP farmer welfare representations.\nColachel fishing harbor infrastructural expansion.",
    "key_actions_ta": "நாகர்கோவில் - திருவனந்தபுரம் நான்கு வழிச்சாலை பணிகள்.\nரப்பர் மற்றும் தென்னை விவசாயிகளுக்கு நியாயமான ஆதார விலை.\nகுளச்சல் மீன்பிடி துறைமுக உள்கட்டமைப்பு விரிவாக்கம்.",
    "is_active": true
  },
  {
    "district_slug": "thanjavur",
    "district_name": "Thanjavur",
    "district_name_ta": "தஞ்சாவூர்",
    "mla_name": "T. K. G. Neelamegam",
    "mla_name_ta": "டி. கே. ஜி. நீலமேகம்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Thanjavur (174)",
    "constituency_ta": "தஞ்சாவூர் (174)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 48.6,
    "winning_margin": 12100,
    "performance_score": 82,
    "key_actions_en": "Cauvery delta water release schedule advocacy.\nDirect Paddy Procurement Centers (DPC) moisture limit relaxation.\nThanjavur heritage moat and temple corridor preservation.",
    "key_actions_ta": "காவிரி டெல்டா நீர் பாசனம் குறித்த சட்டசபைக் குரல்.\nநேரடி நெல் கொள்முதல் நிலையங்களில் ஈரப்பத தளர்வு கோரிக்கை.\nதஞ்சை பெரியகோயில் அகழி மற்றும் பாரம்பரிய நடைபாதை பராமரிப்பு.",
    "is_active": true
  },
  {
    "district_slug": "tiruvarur",
    "district_name": "Tiruvarur",
    "district_name_ta": "திருவாரூர்",
    "mla_name": "T. R. B. Rajaa",
    "mla_name_ta": "டி. ஆர். பி. ராஜா",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Mannargudi (167)",
    "constituency_ta": "மன்னார்குடி (167)",
    "photo_url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7e/T_R_B_Rajaa_at_DMK_Party_Committee_Meeting.jpg/500px-T_R_B_Rajaa_at_DMK_Party_Committee_Meeting.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "elected_date": "2026-05-04",
    "vote_share": 49.5,
    "winning_margin": 14700,
    "performance_score": 87,
    "key_actions_en": "Senior DMK leader on commerce, industrial investment, and delta growth.\nAgricultural cold storage facilities for paddy and pulses.\nMannargudi municipal water supply augmentation.",
    "key_actions_ta": "சட்டசபையில் தொழில் முதலீடு மற்றும் டெல்டா வளர்ச்சி குறித்த திமுக குரல்.\nநெல் மற்றும் பருப்பு விவசாயிகளுக்கு குளிர்பதன கிடங்குகள்.\nமன்னார்குடி நகராட்சி குடிநீர் திட்ட விரிவாக்கம்.",
    "is_active": true
  },
  {
    "district_slug": "nagapattinam",
    "district_name": "Nagapattinam",
    "district_name_ta": "நாகப்பட்டினம்",
    "mla_name": "Aloor Shanavas",
    "mla_name_ta": "ஆளூர் ஷாநவாஸ்",
    "party_slug": "vck",
    "party_name": "VCK",
    "constituency": "Nagapattinam (163)",
    "constituency_ta": "நாகப்பட்டினம் (163)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 47.9,
    "winning_margin": 9800,
    "performance_score": 84,
    "key_actions_en": "Nagapattinam-Kankesanthurai international passenger ferry follow-up.\nCoastal sea wall protection in erosion-prone fishing villages.\nSatellite trackers for deep-sea fishing safety.",
    "key_actions_ta": "நாகப்பட்டினம் - காங்கேசன்துறை சர்வதேச பயணிகள் கப்பல் போக்குவரத்து.\nமீனவ கிராமங்களில் கடல் அரிப்பு தடுப்பு சுவர் அமைத்தல்.\nஆழ்கடல் மீனவர்களுக்கு செயற்கைக்கோள் தகவல் தொடர்பு சாதனங்கள்.",
    "is_active": true
  },
  {
    "district_slug": "mayiladuthurai",
    "district_name": "Mayiladuthurai",
    "district_name_ta": "மயிலாடுதுறை",
    "mla_name": "S. Rajakumar",
    "mla_name_ta": "எஸ். ராஜகுமார்",
    "party_slug": "inc",
    "party_name": "INC",
    "constituency": "Mayiladuthurai (160)",
    "constituency_ta": "மயிலாடுதுறை (160)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 44.8,
    "winning_margin": 4100,
    "performance_score": 80,
    "key_actions_en": "New Mayiladuthurai District headquarters infrastructure follow-up.\nPoompuhar tourist beach development.\nTail-end canal desilting for irrigation.",
    "key_actions_ta": "புதிய மயிலாடுதுறை மாவட்ட ஆட்சியர் அலுவலக கட்டமைப்பு பணிகள்.\nபூம்புகார் சுற்றுலா கடற்கரை மேம்பாடு.\nகடைமடை பாசன கால்வாய் தூர்வாருதல்.",
    "is_active": true
  },
  {
    "district_slug": "cuddalore",
    "district_name": "Cuddalore",
    "district_name_ta": "கடலூர்",
    "mla_name": "M. C. Sampath",
    "mla_name_ta": "எம். சி. சம்பத்",
    "party_slug": "aiadmk",
    "party_name": "AIADMK",
    "constituency": "Cuddalore (153)",
    "constituency_ta": "கடலூர் (153)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 46.9,
    "winning_margin": 7800,
    "performance_score": 82,
    "key_actions_en": "Cuddalore SIPCOT environmental monitoring and zero-pollution enforcement.\nCoastal storm shelter maintenance.\nNLC land compensation grievance settlement representations.",
    "key_actions_ta": "கடலூர் சிப்காட் சுற்றுச்சூழல் மாசுபாடு தடுப்பு நடவடிக்கைகள்.\nகடலோர புயல் பாதுகாப்பு மையங்கள் பராமரிப்பு.\nஎன்எல்சி நில இழப்பீடு கோரிக்கைகள் சட்டமன்றத்தில் முன்வைத்தல்.",
    "is_active": true
  },
  {
    "district_slug": "kallakurichi",
    "district_name": "Kallakurichi",
    "district_name_ta": "கள்ளக்குறிச்சி",
    "mla_name": "M. Senthilkumar",
    "mla_name_ta": "எம். செந்தில்குமார்",
    "party_slug": "tvk",
    "party_name": "TVK",
    "constituency": "Kallakurichi (SC) (080)",
    "constituency_ta": "கள்ளக்குறிச்சி (SC) (080)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 51.3,
    "winning_margin": 22400,
    "performance_score": 84,
    "key_actions_en": "Manimuktha river check dams for agricultural recharge.\nKallakurichi government medical college hospital super-specialty units.\nSugarcane farmers pending mill payment settlement drives.",
    "key_actions_ta": "மணிமுக்தா நதி தடுப்பணைகள் அமைக்கும் பணிகள்.\nகள்ளக்குறிச்சி அரசு மருத்துவக் கல்லூரி மருத்துவமனை அதிநவீன வசதிகள்.\nகரும்பு விவசாயிகளுக்கு ஆலை நிலுவைத் தொகை பெற்றுத்தரும் முயற்சிகள்.",
    "is_active": true
  },
  {
    "district_slug": "perambalur",
    "district_name": "Perambalur",
    "district_name_ta": "பெரம்பலூர்",
    "mla_name": "M. Prabhakaran",
    "mla_name_ta": "எம். பிரபாகரன்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Perambalur (SC) (147)",
    "constituency_ta": "பெரம்பலூர் (SC) (147)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 45.8,
    "winning_margin": 6200,
    "performance_score": 80,
    "key_actions_en": "Small onion cold storage network expansion.\nSIPCOT Padalur employment drives for rural youth.\nDrinking water pipeline distribution across drought-prone blocks.",
    "key_actions_ta": "சின்ன வெங்காயம் குளிர்பதன கிடங்கு வசதிகள் அமைத்தல்.\nசிப்காட் பாடாலூர் தொழிற்பேட்டை வேலைவாய்ப்பு முகாம்கள்.\nவறட்சி பாதித்த ஒன்றியங்களில் குடிநீர் குழாய் திட்டங்கள்.",
    "is_active": true
  },
  {
    "district_slug": "ariyalur",
    "district_name": "Ariyalur",
    "district_name_ta": "அரியலூர்",
    "mla_name": "K. Chinnappa",
    "mla_name_ta": "கா. சின்னப்பா",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Ariyalur (149)",
    "constituency_ta": "அரியலூர் (149)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 46.1,
    "winning_margin": 4900,
    "performance_score": 81,
    "key_actions_en": "Cement industrial cluster local youth employment petitions.\nGangaikonda Cholapuram heritage museum development.\nMarudaiyaru river flood mitigation barrage.",
    "key_actions_ta": "சிமெண்ட் ஆலைகளில் உள்ளூர் இளைஞர்களுக்கு வேலைவாய்ப்பு கோரிக்கைகள்.\nகங்கைகொண்ட சோழபுரம் அருங்காட்சியக பணிகள்.\nமருதையாறு வெள்ளத் தடுப்பு கதவணை அமைத்தல்.",
    "is_active": true
  },
  {
    "district_slug": "pudukkottai",
    "district_name": "Pudukkottai",
    "district_name_ta": "புதுக்கோட்டை",
    "mla_name": "Dr. V. Muthuraja",
    "mla_name_ta": "மருத்துவர் வி. முத்துராஜா",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Pudukkottai (180)",
    "constituency_ta": "புதுக்கோட்டை (180)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 47.8,
    "winning_margin": 8900,
    "performance_score": 81,
    "key_actions_en": "Pudukkottai medical college cardiology wing upgrades.\nCauvery-Gundar river linking canal works oversight.\nMachuvadi railway gate overbridge work completion.",
    "key_actions_ta": "புதுக்கோட்டை மருத்துவக் கல்லூரி இருதய பிரிவு நவீனமயமாக்கல்.\nகாவிரி-குண்டாறு இணைப்பு கால்வாய் திட்டப் பணிகள் மேற்பார்வை.\nமச்சுவாடி ரயில்வே கேட் மேம்பால பணிகள் நிறைவு.",
    "is_active": true
  },
  {
    "district_slug": "tiruvannamalai",
    "district_name": "Tiruvannamalai",
    "district_name_ta": "திருவண்ணாமலை",
    "mla_name": "E. V. Velu",
    "mla_name_ta": "எ. வ. வேலு",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Tiruvannamalai (063)",
    "constituency_ta": "திருவண்ணாமலை (063)",
    "photo_url": null,
    "elected_date": "2026-05-04",
    "vote_share": 52.1,
    "winning_margin": 21500,
    "performance_score": 87,
    "key_actions_en": "Girivalam path pedestrian safety, solar lighting, and pilgrim amenities.\nTiruvannamalai outer ring road project completion.\nDistrict highways four-laning and bridge construction.",
    "key_actions_ta": "கிரிவலப் பாதை நடைபயிற்சி பாதுகாப்பு மற்றும் பக்தர்களுக்கான வசதிகள்.\nதிருவண்ணாமலை வெளிவட்டச் சாலைப் பணிகள் நிறைவு.\nமாவட்ட நெடுஞ்சாலைகள் நான்கு வழிச்சாலை மற்றும் பாலங்கள் கட்டுதல்.",
    "is_active": true
  }
];

export const MLAS_BY_DISTRICT = TN_MLAS_DATA.reduce((acc, mla) => {
  acc[mla.district_slug] = mla;
  return acc;
}, {});
