// Verified data of incumbent MLAs across all 38 districts of Tamil Nadu
// 16th Tamil Nadu Legislative Assembly (Official Assembly & Election Records)

export const TN_MLAS_DATA = [
  {
    "district_slug": "chennai",
    "district_name": "Chennai",
    "district_name_ta": "சென்னை",
    "mla_name": "M. K. Stalin",
    "mla_name_ta": "மு. க. ஸ்டாலின்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Kolathur (013)",
    "constituency_ta": "கொளத்தூர் (013)",
    "photo_url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9d/The_Chief_Minister_of_Tamil_Nadu%2C_Thiru_MK_Stalin.jpg/500px-The_Chief_Minister_of_Tamil_Nadu%2C_Thiru_MK_Stalin.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "elected_date": "2021-05-02",
    "vote_share": 60.86,
    "winning_margin": 70384,
    "performance_score": 94,
    "key_actions_en": "Singara Chennai 2.0 urban modernization.\nExtensive stormwater drain construction across flood-prone lowlands.\nCMDA North Chennai Development Board infrastructure packages.",
    "key_actions_ta": "சிங்கார சென்னை 2.0 நகர்ப்புற கட்டமைப்பு பணிகள்.\nவெள்ள பாதிப்பு பகுதிகளில் விரிவான மழைநீர் வடிகால் அமைப்புகள்.\nவட சென்னை வளர்ச்சி வாரியம் மூலம் கட்டமைப்பு திட்டங்கள்.",
    "is_active": true
  },
  {
    "district_slug": "salem",
    "district_name": "Salem",
    "district_name_ta": "சேலம்",
    "mla_name": "Edappadi K. Palaniswami",
    "mla_name_ta": "எடப்பாடி கே. பழனிசாமி",
    "party_slug": "aiadmk",
    "party_name": "AIADMK",
    "constituency": "Edappadi (086)",
    "constituency_ta": "எடப்பாடி (086)",
    "photo_url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f7/K._Palaniswami.jpg/500px-K._Palaniswami.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "elected_date": "2021-05-02",
    "vote_share": 65.97,
    "winning_margin": 93802,
    "performance_score": 88,
    "key_actions_en": "Assembly advocacy for textile units and agricultural power subsidies.\nMettur surplus water lake filling scheme review.\nSalem arterial road network maintenance representations.",
    "key_actions_ta": "விவசாயிகள் மின் மானியம் மற்றும் விசைத்தறி நெசவாளர்கள் நலன் குறித்த சட்டமன்ற குரல்.\nமேட்டூர் உபரி நீர் திட்ட கண்காணிப்பு.\nசேலம் முக்கிய சாலைகள் சீரமைப்பு கோரிக்கைகள்.",
    "is_active": true
  },
  {
    "district_slug": "coimbatore",
    "district_name": "Coimbatore",
    "district_name_ta": "கோயம்புத்தூர்",
    "mla_name": "Vanathi Srinivasan",
    "mla_name_ta": "வானதி சீனிவாசன்",
    "party_slug": "bjp",
    "party_name": "BJP",
    "constituency": "Coimbatore South (120)",
    "constituency_ta": "கோயம்புத்தூர் தெற்கு (120)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 34.38,
    "winning_margin": 1728,
    "performance_score": 82,
    "key_actions_en": "Defense industrial corridor and MSME foundry representation to Union Ministries.\nCoimbatore Airport runway expansion land acquisition follow-up.\nSmart City dug-up road restoration grievance drives.",
    "key_actions_ta": "சிறு-குறு தொழில் நிறுவனங்கள் மற்றும் பவுண்டரி கோரிக்கைகள் மத்திய அமைச்சகத்திடம் சமர்ப்பிப்பு.\nகோவை விமான நிலைய விரிவாக்க நில எடுப்பு துரிதப்படுத்தல்.\nஸ்மார்ட் சிட்டி தோண்டப்பட்ட சாலைகள் சீரமைப்பு நடவடிக்கைகள்.",
    "is_active": true
  },
  {
    "district_slug": "madurai",
    "district_name": "Madurai",
    "district_name_ta": "மதுரை",
    "mla_name": "Dr. Palanivel Thiagarajan",
    "mla_name_ta": "முனைவர் பழனிவேல் தியாகராஜன்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Madurai Central (191)",
    "constituency_ta": "மதுரை மத்தியம் (191)",
    "photo_url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d1/Palanivel_Thiaga_Rajan%2C_Minister_for_Information_Technology_%26_Digital_Services%2C_Government_of_Tamil_Nadu%2C_keynoting_the_Horasis_India_Meeting_%28Cropped%29.jpg/500px-Palanivel_Thiaga_Rajan%2C_Minister_for_Information_Technology_%26_Digital_Services%2C_Government_of_Tamil_Nadu%2C_keynoting_the_Horasis_India_Meeting_%28Cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "elected_date": "2021-05-02",
    "vote_share": 58.7,
    "winning_margin": 34176,
    "performance_score": 91,
    "key_actions_en": "Madurai Metro Rail Project DPR and funding clearance.\nKalaignar Memorial Centenary Library establishment and digital knowledge hub.\nVadapalanji IT Park job recruitment drives and tech incubation.",
    "key_actions_ta": "மதுரை மெட்ரோ ரயில் விரிவான திட்ட அறிக்கை (DPR) ஒப்புதல்.\nகலைஞர் நூற்றாண்டு நூலக நவீன அறிவு மையம்.\nவடபழஞ்சி தகவல் தொழில்நுட்ப பூங்கா வேலைவாய்ப்பு விரிவாக்கம்.",
    "is_active": true
  },
  {
    "district_slug": "tiruchirappalli",
    "district_name": "Tiruchirappalli",
    "district_name_ta": "திருச்சிராப்பள்ளி",
    "mla_name": "K. N. Nehru",
    "mla_name_ta": "கே. என். நேரு",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Tiruchirappalli West (140)",
    "constituency_ta": "திருச்சிராப்பள்ளி மேற்கு (140)",
    "photo_url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/11/Nehru_in_an_public_meeting.jpg/500px-Nehru_in_an_public_meeting.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "elected_date": "2021-05-02",
    "vote_share": 64.52,
    "winning_margin": 85109,
    "performance_score": 89,
    "key_actions_en": "Panjapur integrated mega bus terminal construction.\nTrichy elevated corridor connecting Head Post Office to Chathiram.\nUyyakondan canal cleaning and flood diversion bund strengthening.",
    "key_actions_ta": "பஞ்சப்பூர் ஒருங்கிணைந்த பேருந்து முனையப் பணிகள்.\nதலைமை தபால் நிலையம் முதல் சத்திரம் வரையிலான உயர்மட்ட மேம்பாலம்.\nஉய்யக்கொண்டான் கால்வாய் தூர்வாருதல் மற்றும் கரைகள் பலப்படுத்துதல்.",
    "is_active": true
  },
  {
    "district_slug": "tirunelveli",
    "district_name": "Tirunelveli",
    "district_name_ta": "திருநெல்வேலி",
    "mla_name": "Nainar Nagendran",
    "mla_name_ta": "நயினார் நாகேந்திரன்",
    "party_slug": "bjp",
    "party_name": "BJP",
    "constituency": "Tirunelveli (224)",
    "constituency_ta": "திருநெல்வேலி (224)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 46.7,
    "winning_margin": 23107,
    "performance_score": 81,
    "key_actions_en": "Thamirabarani river sewage prevention and cleaning projects.\nTirunelveli Junction railway terminal infrastructure representations.\nHandloom weaver welfare and wage revision representations.",
    "key_actions_ta": "தாமிரபரணி நதி கழிவுநீர் கலப்பு தடுப்பு பணிகள்.\nதிருநெல்வேலி ரயில் சந்திப்பு கூடுதல் முனைய வசதிகள்.\nநெசவாளர் நல வாரியம் மற்றும் கூலி உயர்வு கோரிக்கைகள்.",
    "is_active": true
  },
  {
    "district_slug": "thoothukudi",
    "district_name": "Thoothukudi",
    "district_name_ta": "தூத்துக்குடி",
    "mla_name": "P. Geetha Jeevan",
    "mla_name_ta": "பி. கீதா ஜீவன்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Thoothukudi (215)",
    "constituency_ta": "தூத்துக்குடி (215)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 57.58,
    "winning_margin": 50310,
    "performance_score": 86,
    "key_actions_en": "Stormwater pump houses and flood mitigation systems across Thoothukudi Corporation.\nSalt pan workers monsoon assistance distribution.\nV.O.C. Port industrial corridor employment initiatives.",
    "key_actions_ta": "தூத்துக்குடி மாநகராட்சி மழைநீர் வடிகால் பம்பிங் நிலையங்கள் அமைப்பு.\nஉப்பளத் தொழிலாளர்களுக்கு மழைக்கால நிவாரண நிதி விநியோகம்.\nவ.உ.சி துறைமுக தொழிற்பேட்டை வேலைவாய்ப்பு முகாம்கள்.",
    "is_active": true
  },
  {
    "district_slug": "tiruvannamalai",
    "district_name": "Tiruvannamalai",
    "district_name_ta": "திருவண்ணாமலை",
    "mla_name": "E. V. Velu",
    "mla_name_ta": "எ. வ. வேலு",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Tiruvannamalai (063)",
    "constituency_ta": "திருவண்ணாமலை (063)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 61.64,
    "winning_margin": 94673,
    "performance_score": 88,
    "key_actions_en": "Girivalam path pedestrian safety, solar lighting, and pilgrim amenities.\nTiruvannamalai outer ring road project completion.\nDistrict arterial highways four-laning and bridge construction.",
    "key_actions_ta": "கிரிவலப் பாதை நடைபயிற்சி பாதுகாப்பு, சோலார் விளக்குகள் மற்றும் பக்தர்களுக்கான வசதிகள்.\nதிருவண்ணாமலை வெளிவட்டச் சாலைப் பணிகள் நிறைவு.\nமாவட்ட நெடுஞ்சாலைகள் நான்கு வழிச்சாலை மற்றும் புதிய பாலங்கள் கட்டுதல்.",
    "is_active": true
  },
  {
    "district_slug": "erode",
    "district_name": "Erode",
    "district_name_ta": "ஈரோடு",
    "mla_name": "E. V. K. S. Elangovan",
    "mla_name_ta": "ஈ. வி. கே. எஸ். இளங்கோவன்",
    "party_slug": "inc",
    "party_name": "INC",
    "constituency": "Erode East (098)",
    "constituency_ta": "ஈரோடு கிழக்கு (098)",
    "photo_url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/46/E._V._K._S._Elangovan_at_Marriage_Function_12.jpg/500px-E._V._K._S._Elangovan_at_Marriage_Function_12.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "elected_date": "2023-03-02",
    "vote_share": 64.58,
    "winning_margin": 66233,
    "performance_score": 83,
    "key_actions_en": "Common effluent treatment modernization for textile dyeing units.\nPerumpallam canal revival and concrete revetment wall.\nNethaji daily market modern trade complex commissioning.",
    "key_actions_ta": "ஜவுளி சாய ஆலைகளுக்கான கழிவுநீர் சுத்திகரிப்பு ஆலை நவீனமயமாக்கல்.\nபெரும்பள்ளம் ஓடை தூர்வாருதல் மற்றும் கான்கிரீட் தடுப்புச்சுவர்.\nநேதாஜி காய்கறி தினசரி சந்தை நவீன வளாகம் பயன்பாட்டிற்கு கொண்டு வருதல்.",
    "is_active": true
  },
  {
    "district_slug": "karur",
    "district_name": "Karur",
    "district_name_ta": "கரூர்",
    "mla_name": "V. Senthilbalaji",
    "mla_name_ta": "வி. செந்தில்பாலாஜி",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Karur (135)",
    "constituency_ta": "கரூர் (135)",
    "photo_url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/84/Senthil_Balaji_Official_Potrait.png/500px-Senthil_Balaji_Official_Potrait.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "elected_date": "2021-05-02",
    "vote_share": 49.33,
    "winning_margin": 12448,
    "performance_score": 87,
    "key_actions_en": "Mayanur barrage water regulation and irrigation canal lining.\nKarur textile export park infrastructural upgrades.\nAmaravathi river bank protection retaining wall.",
    "key_actions_ta": "மாயனூர் கதவணை நீர் ஒழுங்குமுறை மற்றும் பாசன வாய்க்கால் சீரமைப்பு.\nகரூர் ஜவுளி ஏற்றுமதி பூங்கா கட்டமைப்பு மேம்பாடுகள்.\nஅமராவதி ஆற்றுப்படுகை தடுப்புச்சுவர் அமைக்கும் பணிகள்.",
    "is_active": true
  },
  {
    "district_slug": "ranipet",
    "district_name": "Ranipet",
    "district_name_ta": "ராணிப்பேட்டை",
    "mla_name": "R. Gandhi",
    "mla_name_ta": "ஆர். காந்தி",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Ranipet (041)",
    "constituency_ta": "ராணிப்பேட்டை (041)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 49.79,
    "winning_margin": 16498,
    "performance_score": 85,
    "key_actions_en": "New Ranipet District Collectorate complex inauguration.\nSIPCOT leather industrial effluent treatment modernization.\nPalar check dam construction for groundwater recharge.",
    "key_actions_ta": "ராணிப்பேட்டை புதிய மாவட்ட ஆட்சியர் பெருந்திட்ட வளாகம் திறப்பு.\nசிப்காட் தோல் பதனிடும் கழிவுநீர் சுத்திகரிப்பு நவீனமயமாக்கல்.\nபாலாறு தடுப்பணைகள் மூலம் நிலத்தடி நீர்மட்டம் உயர்த்துதல்.",
    "is_active": true
  },
  {
    "district_slug": "theni",
    "district_name": "Theni",
    "district_name_ta": "தேனி",
    "mla_name": "O. Panneerselvam",
    "mla_name_ta": "ஓ. பன்னீர்செல்வம்",
    "party_slug": "independent",
    "party_name": "Independent",
    "constituency": "Bodinayakanur (199)",
    "constituency_ta": "போடிநாயக்கனூர் (199)",
    "photo_url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0a/O._Panneerselvam.jpg/500px-O._Panneerselvam.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "elected_date": "2021-05-02",
    "vote_share": 46.56,
    "winning_margin": 11021,
    "performance_score": 80,
    "key_actions_en": "Mullaperiyar dam water storage maintenance advocacy.\nCardamom and tea planter transport subsidy follow-ups.\n18th canal irrigation water supply release representations.",
    "key_actions_ta": "முல்லைப்பெரியாறு அணை நீர்மட்ட உரிமைகள் குறித்த சட்டசபைக் குரல்.\nஏலக்காய் மற்றும் தேயிலை விவசாயிகள் போக்குவரத்து நிவாரண முயற்சிகள்.\n18-ம் கால்வாய் பாசன நீர் திறப்பு கோரிக்கைகள்.",
    "is_active": true
  },
  {
    "district_slug": "nagapattinam",
    "district_name": "Nagapattinam",
    "district_name_ta": "நாகப்பட்டினம்",
    "mla_name": "Aloor Shanavas",
    "mla_name_ta": "ஆளூர் ஷாநவாஸ்",
    "party_slug": "vck",
    "party_name": "VCK",
    "constituency": "Nagapattinam (163)",
    "constituency_ta": "நாகப்பட்டினம் (163)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 46.23,
    "winning_margin": 7238,
    "performance_score": 84,
    "key_actions_en": "Nagapattinam-Kankesanthurai international ferry service connectivity.\nCoastal protection sea wall construction in vulnerable fishing hamlets.\nFishermen high-seas satellite tracker and communication drives.",
    "key_actions_ta": "நாகப்பட்டினம் - காங்கேசன்துறை சர்வதேச பயணிகள் கப்பல் போக்குவரத்து முயற்சிகள்.\nமீனவ கிராமங்களில் கடல் அரிப்பு தடுப்பு சுவர் அமைத்தல்.\nஆழ்கடல் மீனவர்களுக்கு செயற்கைக்கோள் தகவல் தொடர்பு உபகரணங்கள் வழங்கல்.",
    "is_active": true
  },
  {
    "district_slug": "kanniyakumari",
    "district_name": "Kanniyakumari",
    "district_name_ta": "கன்னியாகுமரி",
    "mla_name": "M. R. Gandhi",
    "mla_name_ta": "எம். ஆர். காந்தி",
    "party_slug": "bjp",
    "party_name": "BJP",
    "constituency": "Nagercoil (230)",
    "constituency_ta": "நாகர்கோவில் (230)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 48.21,
    "winning_margin": 11669,
    "performance_score": 80,
    "key_actions_en": "Four-lane highway works monitoring connecting Nagercoil to Trivandrum.\nRubber and coconut MSP farmer welfare representations.\nColachel fishing harbor infrastructural expansion.",
    "key_actions_ta": "நாகர்கோவில் - திருவனந்தபுரம் நான்கு வழிச்சாலை பணிகளை விரைவுபடுத்துதல்.\nரப்பர் மற்றும் தென்னை விவசாயிகளுக்கு நியாயமான குறைந்தபட்ச ஆதார விலை கோரிக்கை.\nகுளச்சல் மீன்பிடி துறைமுக உள்கட்டமைப்பு விரிவாக்கம்.",
    "is_active": true
  },
  {
    "district_slug": "dindigul",
    "district_name": "Dindigul",
    "district_name_ta": "திண்டுக்கல்",
    "mla_name": "Dindigul C. Sreenivasan",
    "mla_name_ta": "திண்டுக்கல் சி. சீனிவாசன்",
    "party_slug": "aiadmk",
    "party_name": "AIADMK",
    "constituency": "Dindigul (127)",
    "constituency_ta": "திண்டுக்கல் (127)",
    "photo_url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/14/C._Sreenivasan.jpg/500px-C._Sreenivasan.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "elected_date": "2021-05-02",
    "vote_share": 46.9,
    "winning_margin": 17797,
    "performance_score": 81,
    "key_actions_en": "Lock industry and brassware artisan welfare representations.\nAthoor Kamarajar Sagar dam drinking water pipeline monitoring.\nSirumalai tourist hill road maintenance petition.",
    "key_actions_ta": "திண்டுக்கல் பூட்டு மற்றும் பித்தளை தொழிலாளர்களுக்கு நலவாரிய சலுகைகள் கோரிக்கை.\nஆத்தூர் காமராஜர் நீர்த்தேக்க குடிநீர் குழாய் பராமரிப்பு.\nசிறுமலை சுற்றுலா மலைப்பாதை சீரமைப்பு மனு.",
    "is_active": true
  },
  {
    "district_slug": "vellore",
    "district_name": "Vellore",
    "district_name_ta": "வேலூர்",
    "mla_name": "Duraimurugan",
    "mla_name_ta": "துரைமுருகன்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Katpadi (040)",
    "constituency_ta": "காட்பாடி (040)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 46.75,
    "winning_margin": 746,
    "performance_score": 90,
    "key_actions_en": "Leader of the House and Water Resources Minister.\nPalar river check dams and sub-surface dykes execution.\nVellore Abdullapuram airport development follow-up.",
    "key_actions_ta": "சட்டமன்ற முன்னவர் மற்றும் நீர்வளத்துறை அமைச்சர்.\nபாலாறு தடுப்பணைகள் மற்றும் நிலத்தடி நீர் செறிவூட்டும் திட்டங்கள்.\nவேலூர் அப்துல்லாபுரம் விமான நிலைய விரிவாக்கம்.",
    "is_active": true
  },
  {
    "district_slug": "thanjavur",
    "district_name": "Thanjavur",
    "district_name_ta": "தஞ்சாவூர்",
    "mla_name": "T. K. G. Neelamegam",
    "mla_name_ta": "டி. கே. ஜி. நீலமேகம்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Thanjavur (174)",
    "constituency_ta": "தஞ்சாவூர் (174)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 53.25,
    "winning_margin": 47449,
    "performance_score": 83,
    "key_actions_en": "Grand Anicut canal desilting and water release schedule.\nDirect Paddy Procurement Centers (DPC) moisture limit relaxation.\nThanjavur Smart City heritage moat restoration.",
    "key_actions_ta": "கல்லணை கால்வாய் தூர்வாருதல் மற்றும் நீர் ஒழுங்குமுறை.\nநேரடி நெல் கொள்முதல் நிலையங்களில் (DPC) ஈரப்பத தளர்வு கோரிக்கை.\nதஞ்சை ஸ்மார்ட் சிட்டி அகழி புனரமைப்பு.",
    "is_active": true
  },
  {
    "district_slug": "kancheepuram",
    "district_name": "Kancheepuram",
    "district_name_ta": "காஞ்சிபுரம்",
    "mla_name": "C. V. M. P. Ezhilarasan",
    "mla_name_ta": "சி. வி. எம். பி. எழிலரசன்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Kancheepuram (037)",
    "constituency_ta": "காஞ்சிபுரம் (037)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 44.77,
    "winning_margin": 11595,
    "performance_score": 83,
    "key_actions_en": "Silk weavers raw silk subsidy distribution and welfare boards.\nVegavathi river rejuvenation and encroachment clearance.\nTemple town ring road and pilgrim parking facilities.",
    "key_actions_ta": "பட்டு நெசவாளர்களுக்கு மானிய விலை கச்சா பட்டு விநியோகம்.\nவேகவதி நதி தூர்வாருதல் மற்றும் ஆக்கிரமிப்பு அகற்றம்.\nகோயில் நகர சுற்றுவட்டச் சாலை மற்றும் வாகன நிறுத்துமிடம்.",
    "is_active": true
  },
  {
    "district_slug": "namakkal",
    "district_name": "Namakkal",
    "district_name_ta": "நாமக்கல்",
    "mla_name": "P. Ramalingam",
    "mla_name_ta": "பெ. ராமலிங்கம்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Namakkal (095)",
    "constituency_ta": "நாமக்கல் (095)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 51.52,
    "winning_margin": 27861,
    "performance_score": 81,
    "key_actions_en": "Poultry industry feed price subsidy representations.\nLorry body building industrial cluster amenities.\nMohanur railway overbridge construction.",
    "key_actions_ta": "கோழிப்பண்ணை தீவன விலை மானிய கோரிக்கை.\nலாரி கூண்டு கட்டும் தொழில் கூட்டமைப்பு அடிப்படை வசதிகள்.\nமோகனூர் ரயில்வே மேம்பாலம் அமைக்கும் பணி.",
    "is_active": true
  },
  {
    "district_slug": "nilgiris",
    "district_name": "Nilgiris",
    "district_name_ta": "நீலகிரி",
    "mla_name": "R. Ganesh",
    "mla_name_ta": "ஆர். கணேஷ்",
    "party_slug": "inc",
    "party_name": "INC",
    "constituency": "Udhagamandalam (108)",
    "constituency_ta": "உதகமண்டலம் (108)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 46.9,
    "winning_margin": 5348,
    "performance_score": 80,
    "key_actions_en": "Small tea growers green leaf minimum floor price guarantee.\nHuman-wildlife conflict rapid response squad enhancement.\nOoty heritage mountain railway route protection.",
    "key_actions_ta": "சிறு தேயிலை விவசாயிகளுக்கு பசுந்தேயிலை நியாய விலை உத்தரவாதம்.\nமனித-விலங்கு மோதல் தடுப்பு விரைவுப் படை பலப்படுத்துதல்.\nஊட்டி பாரம்பரிய மலை ரயில் பாதை பாதுகாப்பு.",
    "is_active": true
  },
  {
    "district_slug": "perambalur",
    "district_name": "Perambalur",
    "district_name_ta": "பெரம்பலூர்",
    "mla_name": "M. Prabhakaran",
    "mla_name_ta": "எம். பிரபாகரன்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Perambalur (SC) (147)",
    "constituency_ta": "பெரம்பலூர் (SC) (147)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 48.06,
    "winning_margin": 12177,
    "performance_score": 80,
    "key_actions_en": "Small onion cold storage warehouse network.\nSIPCOT Padalur industrial estate employment creation.\nDrinking water pipeline distribution across drought-prone blocks.",
    "key_actions_ta": "சின்ன வெங்காயம் குளிர்பதன கிடங்கு வசதிகள் அமைத்தல்.\nசிப்காட் பாடாலூர் தொழிற்பேட்டை வேலைவாய்ப்பு முகாம்கள்.\nவறட்சி பாதித்த ஒன்றியங்களில் குடிநீர் குழாய் திட்டங்கள்.",
    "is_active": true
  },
  {
    "district_slug": "pudukkottai",
    "district_name": "Pudukkottai",
    "district_name_ta": "புதுக்கோட்டை",
    "mla_name": "S. Regupathy",
    "mla_name_ta": "எஸ். ரகுபதி",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Tirumayam (182)",
    "constituency_ta": "திருமயம் (182)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 49.03,
    "winning_margin": 1382,
    "performance_score": 88,
    "key_actions_en": "Minister for Law, Courts and Prisons.\nCauvery-Vaigai-Gundar river linking monitoring in Pudukkottai section.\nNew combined court buildings and judicial infrastructure.",
    "key_actions_ta": "சட்டத்துறை, நீதிமன்றங்கள் மற்றும் சிறைச்சாலைகள் அமைச்சர்.\nகாவிரி-வைகை-குண்டாறு இணைப்பு கால்வாய் திட்டப் பணிகள் மேற்பார்வை.\nபுதிய ஒருங்கிணைந்த நீதிமன்ற வளாகக் கட்டமைப்பு.",
    "is_active": true
  },
  {
    "district_slug": "ramanathapuram",
    "district_name": "Ramanathapuram",
    "district_name_ta": "இராமநாதபுரம்",
    "mla_name": "Katharbatcha Muthuramalingam",
    "mla_name_ta": "காதர்பாட்ஷா முத்துராமலிங்கம்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Ramanathapuram (211)",
    "constituency_ta": "இராமநாதபுரம் (211)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 51.88,
    "winning_margin": 50479,
    "performance_score": 82,
    "key_actions_en": "Seawater desalination plant drinking water scheme expansion.\nRamanathapuram chilli (Gundu Milagai) GI tag farmer promotion.\nRameshwaram pilgrimage road and sanitation infrastructure.",
    "key_actions_ta": "கடல்நீரை குடிநீராக்கும் திட்ட விரிவாக்கம்.\nராமநாதபுரம் குண்டு மிளகாய் விவசாயிகளுக்கு ஏற்றுமதி சந்தை வசதிகள்.\nராமேஸ்வரம் புனித யாத்திரை சாலை மற்றும் சுகாதார வசதிகள்.",
    "is_active": true
  },
  {
    "district_slug": "sivaganga",
    "district_name": "Sivaganga",
    "district_name_ta": "சிவகங்கை",
    "mla_name": "KR. Periakaruppan",
    "mla_name_ta": "கே. ஆர். பெரியகருப்பன்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Tiruppattur (185)",
    "constituency_ta": "திருப்பத்தூர் (185)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 49.19,
    "winning_margin": 37374,
    "performance_score": 87,
    "key_actions_en": "Minister for Rural Development, Panchayats and Panchayat Unions.\nRural road connectivity and self-help group revolving fund allocations.\nKeeladi archaeology center infrastructure and transport connectivity.",
    "key_actions_ta": "ஊரக வளர்ச்சி மற்றும் ஊராட்சித் துறை அமைச்சர்.\nகிராமப்புற சாலை மேம்பாடுகள் மற்றும் மகளிர் சுயஉதவிக் குழு சுழல்நிதி.\nகீழடி தொல்லியல் அருங்காட்சியக இணைப்பு வசதிகள்.",
    "is_active": true
  },
  {
    "district_slug": "tenkasi",
    "district_name": "Tenkasi",
    "district_name_ta": "தென்காசி",
    "mla_name": "S. Palani Nadar",
    "mla_name_ta": "எஸ். பழனி நாடார்",
    "party_slug": "inc",
    "party_name": "INC",
    "constituency": "Tenkasi (222)",
    "constituency_ta": "தென்காசி (222)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 41.97,
    "winning_margin": 370,
    "performance_score": 80,
    "key_actions_en": "Courtallam waterfalls tourist amenities and safety renovations.\nTenkasi-Tirunelveli railway electrification and track doubling.\nHorticulture lemon and mango farmers marketing support.",
    "key_actions_ta": "குற்றால அருவிகள் சுற்றுலா பயணிகள் வசதிகள் மற்றும் பாதுகாப்பு மேம்பாடு.\nதென்காசி - நெல்லை ரயில் மின்மயமாக்கல் பணிகள்.\nஎலுமிச்சை மற்றும் மாம்பழ விவசாயிகளுக்கு நேரடி விற்பனை மையம்.",
    "is_active": true
  },
  {
    "district_slug": "tiruppur",
    "district_name": "Tiruppur",
    "district_name_ta": "திருப்பூர்",
    "mla_name": "K. Selvaraj",
    "mla_name_ta": "க. செல்வராஜ்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Tiruppur South (114)",
    "constituency_ta": "திருப்பூர் தெற்கு (114)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 43.11,
    "winning_margin": 4709,
    "performance_score": 82,
    "key_actions_en": "Garment export industry yarn price stability representations.\nNoyyal river rejuvenation and effluent monitoring checkpoints.\nTiruppur city flyover and traffic decongestion projects.",
    "key_actions_ta": "பின்னலாடை தொழில் நூல் விலை நிலைத்தன்மை கோரிக்கைகள்.\nநொய்யல் நதி புனரமைப்பு மற்றும் சுத்திகரிப்பு கண்காணிப்பு.\nதிருப்பூர் மாநகர மேம்பாலம் மற்றும் போக்குவரத்து நெரிசல் தீர்வு.",
    "is_active": true
  },
  {
    "district_slug": "tiruvallur",
    "district_name": "Tiruvallur",
    "district_name_ta": "திருவள்ளூர்",
    "mla_name": "S. M. Nasar",
    "mla_name_ta": "சா. மு. நாசர்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Avadi (006)",
    "constituency_ta": "ஆவடி (006)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 49.94,
    "winning_margin": 55275,
    "performance_score": 85,
    "key_actions_en": "Minister for Minorities Welfare and Non-Resident Tamils Welfare.\nAvadi Municipal Corporation underground drainage scheme.\nOuter ring road industrial logistics park development.",
    "key_actions_ta": "சிறுபான்மையினர் நலன் மற்றும் வெளிநாடு வாழ் தமிழர் நலத்துறை அமைச்சர்.\nஆவடி மாநகராட்சி பாதாள சாக்கடை திட்ட விரிவாக்கம்.\nவெளிவட்டச் சாலை தொழில் லாஜிஸ்டிக்ஸ் பூங்கா.",
    "is_active": true
  },
  {
    "district_slug": "tiruvarur",
    "district_name": "Tiruvarur",
    "district_name_ta": "திருவாரூர்",
    "mla_name": "T. R. B. Rajaa",
    "mla_name_ta": "டி. ஆர். பி. ராஜா",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Mannargudi (167)",
    "constituency_ta": "மன்னார்குடி (167)",
    "photo_url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7e/T_R_B_Rajaa_at_DMK_Party_Committee_Meeting.jpg/500px-T_R_B_Rajaa_at_DMK_Party_Committee_Meeting.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "elected_date": "2021-05-02",
    "vote_share": 45.11,
    "winning_margin": 37393,
    "performance_score": 91,
    "key_actions_en": "Minister for Industries, Investment Promotion and Commerce.\nGlobal Investors Meet (GIM) industrial commitments realization.\nCauvery delta agrarian economy value-added food processing parks.",
    "key_actions_ta": "தொழில், முதலீட்டு ஊக்குவிப்பு மற்றும் வர்த்தகத் துறை அமைச்சர்.\nஉலக முதலீட்டாளர்கள் மாநாட்டு புரிந்துணர்வு ஒப்பந்தங்கள் செயலாக்கம்.\nகாவிரி டெல்டா பகுதியில் உணவு பதப்படுத்தும் தொழிற்பூங்காக்கள்.",
    "is_active": true
  },
  {
    "district_slug": "villupuram",
    "district_name": "Villupuram",
    "district_name_ta": "விழுப்புரம்",
    "mla_name": "Gingee K. S. Masthan",
    "mla_name_ta": "செஞ்சி கே. எஸ். மஸ்தான்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Gingee (073)",
    "constituency_ta": "செஞ்சி (073)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 53.01,
    "winning_margin": 35803,
    "performance_score": 84,
    "key_actions_en": "Gingee fort tourism promotion and light-and-sound show infrastructure.\nDistrict check dam construction across Sankaraparani river.\nAgricultural cold storage facilities for sugarcane and paddy farmers.",
    "key_actions_ta": "செஞ்சிக் கோட்டை சுற்றுலா மேம்பாடு மற்றும் வரலாற்று வளாக வசதிகள்.\nசங்கராபரணி ஆற்றில் தடுப்பணைகள் அமைத்தல்.\nவிவசாயிகளுக்கு குளிர்பதன கிடங்கு மற்றும் நேரடி கொள்முதல் நிலையங்கள்.",
    "is_active": true
  },
  {
    "district_slug": "virudhunagar",
    "district_name": "Virudhunagar",
    "district_name_ta": "விருதுநகர்",
    "mla_name": "Thangam Thennarasu",
    "mla_name_ta": "தங்கம் தென்னரசு",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Tiruchuli (208)",
    "constituency_ta": "திருச்சுழி (208)",
    "photo_url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5a/Thangam_Thennarasu.jpg/500px-Thangam_Thennarasu.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
    "elected_date": "2021-05-02",
    "vote_share": 59.15,
    "winning_margin": 60992,
    "performance_score": 93,
    "key_actions_en": "Minister for Finance and Human Resources Management.\nState revenue deficit reduction and social security scheme funding allocations.\nVirudhunagar mega textile park (PM MITRA) establishment.",
    "key_actions_ta": "நிதி மற்றும் மனிதவள மேலாண்மைத் துறை அமைச்சர்.\nமாநில வருவாய் பற்றாக்குறை குறைப்பு மற்றும் நலத்திட்ட நிதி ஒதுக்கீடுகள்.\nவிருதுநகர் பிஎம் மித்ரா மெகா ஜவுளி பூங்கா அமைக்கும் பணி.",
    "is_active": true
  },
  {
    "district_slug": "ariyalur",
    "district_name": "Ariyalur",
    "district_name_ta": "அரியலூர்",
    "mla_name": "K. Chinnappa",
    "mla_name_ta": "கா. சின்னப்பா",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Ariyalur (149)",
    "constituency_ta": "அரியலூர் (149)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 50.44,
    "winning_margin": 3234,
    "performance_score": 81,
    "key_actions_en": "Cement industrial cluster local youth employment reservation petitions.\nGangaikonda Cholapuram heritage museum development.\nMarudaiyaru river flood mitigation barrage.",
    "key_actions_ta": "சிமெண்ட் ஆலைகளில் உள்ளூர் இளைஞர்களுக்கு வேலைவாய்ப்பு கோரிக்கைகள்.\nகங்கைகொண்ட சோழபுரம் தொல்லியல் அருங்காட்சியக பணிகள்.\nமருதையாறு வெள்ளத் தடுப்பு கதவணை அமைத்தல்.",
    "is_active": true
  },
  {
    "district_slug": "chengalpattu",
    "district_name": "Chengalpattu",
    "district_name_ta": "செங்கல்பட்டு",
    "mla_name": "S. R. Raja",
    "mla_name_ta": "எஸ். ஆர். ராஜா",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Tambaram (031)",
    "constituency_ta": "தாம்பரம் (031)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 46.93,
    "winning_margin": 36824,
    "performance_score": 84,
    "key_actions_en": "Tambaram Corporation underground drainage and flood mitigation.\nGST Road pedestrian skywalks and traffic bottleneck clearances.\nAdyar river rejuvenation in Tambaram-Mudichur stretch.",
    "key_actions_ta": "தாம்பரம் மாநகராட்சி பாதாள சாக்கடை மற்றும் வெள்ளத் தடுப்பு.\nஜிஎஸ்டி சாலை நடைமேம்பாலங்கள் மற்றும் போக்குவரத்து நெரிசல் தீர்வு.\nதாம்பரம்-முடிச்சூர் பகுதியில் அடையாறு புனரமைப்பு.",
    "is_active": true
  },
  {
    "district_slug": "cuddalore",
    "district_name": "Cuddalore",
    "district_name_ta": "கடலூர்",
    "mla_name": "M. R. K. Panneerselvam",
    "mla_name_ta": "எம். ஆர். கே. பன்னீர்செல்வம்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Kurinjipadi (156)",
    "constituency_ta": "குறிஞ்சிப்பாடி (156)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 51.09,
    "winning_margin": 17527,
    "performance_score": 88,
    "key_actions_en": "Minister for Agriculture and Farmers Welfare.\nSeparate Agriculture Budget presentation in Tamil Nadu Assembly.\nCuddalore coastal flood protection and NLC land acquisition dispute mediation.",
    "key_actions_ta": "வேளாண்மை மற்றும் உழவர் நலத்துறை அமைச்சர்.\nதமிழ்நாடு சட்டசபையில் தனி வேளாண் பட்ஜெட் தாக்கல்.\nகடலூர் கடலோர வெள்ளத் தடுப்பு மற்றும் என்எல்சி நில இழப்பீடு பேச்சுவார்த்தைகள்.",
    "is_active": true
  },
  {
    "district_slug": "dharmapuri",
    "district_name": "Dharmapuri",
    "district_name_ta": "தர்மபுரி",
    "mla_name": "S. P. Venkateshwaran",
    "mla_name_ta": "எஸ். பி. வெங்கடேஸ்வரன்",
    "party_slug": "pmk",
    "party_name": "PMK",
    "constituency": "Dharmapuri (084)",
    "constituency_ta": "தர்மபுரி (084)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 49.33,
    "winning_margin": 26860,
    "performance_score": 82,
    "key_actions_en": "Cauvery-Saribanga surplus water irrigation scheme advocacy.\nMorappur-Dharmapuri railway link execution representations.\nMango farmers processing unit and pulp export facilitation.",
    "key_actions_ta": "காவிரி உபரி நீர் பாசன திட்ட கோரிக்கைகள்.\nமொரப்பூர் - தர்மபுரி ரயில்வே இணைப்பு பணிகள் துரிதப்படுத்தல்.\nமாம்பழ கூழ் தயாரிப்பு மற்றும் ஏற்றுமதி வசதிகள்.",
    "is_active": true
  },
  {
    "district_slug": "kallakurichi",
    "district_name": "Kallakurichi",
    "district_name_ta": "கள்ளக்குறிச்சி",
    "mla_name": "K. Vasantham Karthikeyan",
    "mla_name_ta": "வசந்தம் கார்த்திகேயன்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Rishivandiyam (078)",
    "constituency_ta": "ரிஷிவந்தியம் (078)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 48.91,
    "winning_margin": 41728,
    "performance_score": 83,
    "key_actions_en": "Manimuktha river check dam construction for irrigation.\nKallakurichi medical college hospital facilities and oxygen plants.\nSugarcane farmers pending mill payment settlement representations.",
    "key_actions_ta": "மணிமுக்தா நதி தடுப்பணைகள் அமைக்கும் பணிகள்.\nகள்ளக்குறிச்சி மருத்துவக் கல்லூரி மருத்துவமனை வசதிகள்.\nகரும்பு விவசாயிகளுக்கு ஆலை நிலுவைத் தொகை பெற்றுத்தரும் முயற்சிகள்.",
    "is_active": true
  },
  {
    "district_slug": "krishnagiri",
    "district_name": "Krishnagiri",
    "district_name_ta": "கிருஷ்ணகிரி",
    "mla_name": "D. Mathiazhagan",
    "mla_name_ta": "டி. மதியழகன்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Bargur (052)",
    "constituency_ta": "பர்கூர் (052)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 47.93,
    "winning_margin": 12614,
    "performance_score": 82,
    "key_actions_en": "Kelavarapalli dam water quality monitoring and industrial effluent checks.\nHosur auto-ancillary and EV corridor integration.\nGranite and mango processing cold storage units.",
    "key_actions_ta": "கெலவரப்பள்ளி அணை நீர் சுத்திகரிப்பு மற்றும் ஆலை கழிவு கண்காணிப்பு.\nஓசூர் மின்சார வாகன (EV) தொழில் கூட்டமைப்பு வசதிகள்.\nகிரானைட் மற்றும் மாம்பழ பதப்படுத்தும் குளிர்பதன கிடங்குகள்.",
    "is_active": true
  },
  {
    "district_slug": "mayiladuthurai",
    "district_name": "Mayiladuthurai",
    "district_name_ta": "மயிலாடுதுறை",
    "mla_name": "Nivetha M. Murugan",
    "mla_name_ta": "நிவேதா எம். முருகன்",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Poompuhar (161)",
    "constituency_ta": "பூம்புகார் (161)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 46.55,
    "winning_margin": 3299,
    "performance_score": 82,
    "key_actions_en": "New Mayiladuthurai District Collectorate infrastructure follow-ups.\nPoompuhar tourist beach development and coastal protection.\nCauvery tail-end irrigation canal desilting and water release advocacy.",
    "key_actions_ta": "புதிய மயிலாடுதுறை மாவட்ட ஆட்சியர் பெருந்திட்ட பணிகள்.\nபூம்புகார் சுற்றுலா கடற்கரை மேம்பாடு மற்றும் தூண்டில் வளைவு.\nகாவிரி கடைமடை பாசன கால்வாய் தூர்வாருதல்.",
    "is_active": true
  },
  {
    "district_slug": "tirupattur",
    "district_name": "Tirupattur",
    "district_name_ta": "திருப்பத்தூர்",
    "mla_name": "K. Devaraji",
    "mla_name_ta": "கே. தேவராஜி",
    "party_slug": "dmk",
    "party_name": "DMK",
    "constituency": "Jolarpet (049)",
    "constituency_ta": "ஜோலார்பேட்டை (049)",
    "photo_url": null,
    "elected_date": "2021-05-02",
    "vote_share": 46.12,
    "winning_margin": 1091,
    "performance_score": 81,
    "key_actions_en": "Jolarpet railway junction infrastructural expansion.\nYelagiri hills tourist safety road widening and water schemes.\nLeather and shoemaking artisan welfare drives.",
    "key_actions_ta": "ஜோலார்பேட்டை ரயில் சந்திப்பு கூடுதல் வசதிகள்.\nஏலகிரி மலை சுற்றுலா சாலை விரிவாக்கம் மற்றும் குடிநீர் திட்டம்.\nதோல் மற்றும் காலணி தொழிலாளர்கள் நலவாரிய உதவிகள்.",
    "is_active": true
  }
];

export const MLAS_BY_DISTRICT = TN_MLAS_DATA.reduce((acc, mla) => {
  acc[mla.district_slug] = mla;
  return acc;
}, {});
