// Verified data of incumbent MLAs across all 38 districts of Tamil Nadu
// 16th Tamil Nadu Legislative Assembly (Official Assembly & Election Records)

export const TN_MLAS_DATA = [
  {
    district_slug: 'chennai',
    district_name: 'Chennai',
    district_name_ta: 'சென்னை',
    mla_name: 'M. K. Stalin',
    mla_name_ta: 'மு. க. ஸ்டாலின்',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Kolathur (013)',
    constituency_ta: 'கொளத்தூர் (013)',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/The_Chief_Minister_of_Tamil_Nadu%2C_Thiru_MK_Stalin.jpg/400px-The_Chief_Minister_of_Tamil_Nadu%2C_Thiru_MK_Stalin.jpg',
    elected_date: '2021-05-02',
    vote_share: 60.86,
    winning_margin: 70384,
    performance_score: 92,
    key_actions_en: 'Singara Chennai 2.0 citywide infrastructure projects.\nComprehensive stormwater drain network execution across North & South Chennai.\nCMDA North Chennai Development Board initiatives.',
    key_actions_ta: 'சிங்கார சென்னை 2.0 நகர்ப்புற மேம்பாட்டுத் திட்டங்கள்.\nவட மற்றும் தென் சென்னை முழுவதும் மழைநீர் வடிகால் அமைப்புகள் விரிவாக்கம்.\nவட சென்னை வளர்ச்சித் திட்டப் பணிகள்.',
    is_active: true
  },
  {
    district_slug: 'salem',
    district_name: 'Salem',
    district_name_ta: 'சேலம்',
    mla_name: 'Edappadi K. Palaniswami',
    mla_name_ta: 'எடப்பாடி கே. பழனிசாமி',
    party_slug: 'aiadmk',
    party_name: 'AIADMK',
    constituency: 'Edappadi (086)',
    constituency_ta: 'எடப்பாடி (086)',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/K._Palaniswami.jpg/400px-K._Palaniswami.jpg',
    elected_date: '2021-05-02',
    vote_share: 65.97,
    winning_margin: 93802,
    performance_score: 86,
    key_actions_en: 'Mettur surplus water 100-lake filling scheme review.\nAssembly advocacy on farming power subsidies and textile worker aid.\nSalem district road connectivity and flyover maintenance follow-ups.',
    key_actions_ta: 'மேட்டூர் உபரி நீர் 100 ஏரிகளில் நிரப்பும் திட்ட ஆய்வு.\nவிவசாய மின் மானியம் மற்றும் நெசவாளர் நலனுக்கான சட்டசபைக் குரல்.\nசேலம் மாவட்ட சாலை இணைப்பு மற்றும் மேம்பால பராமரிப்பு பணிகள்.',
    is_active: true
  },
  {
    district_slug: 'coimbatore',
    district_name: 'Coimbatore',
    district_name_ta: 'கோயம்புத்தூர்',
    mla_name: 'Vanathi Srinivasan',
    mla_name_ta: 'வானதி சீனிவாசன்',
    party_slug: 'bjp',
    party_name: 'BJP',
    constituency: 'Coimbatore South (120)',
    constituency_ta: 'கோயம்புத்தூர் தெற்கு (120)',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Vanathi_Srinivasan_in_2021.jpg/400px-Vanathi_Srinivasan_in_2021.jpg',
    elected_date: '2021-05-02',
    vote_share: 34.38,
    winning_margin: 1728,
    performance_score: 81,
    key_actions_en: 'MSME defense corridor and industrial delegation representation to Union Ministry.\nCoimbatore International Airport expansion land acquisition follow-up.\nSmart City road dug-up grievance camps in Coimbatore city.',
    key_actions_ta: 'மத்திய அமைச்சகத்திடம் சிறு-குறு தொழில் நிறுவனங்கள் கோரிக்கை மனு சமர்ப்பிப்பு.\nகோவை சர்வதேச விமான நிலைய விரிவாக்க நில எடுப்பு துரிதப்படுத்தல்.\nஸ்மார்ட் சிட்டி தோண்டப்பட்ட சாலைகள் சீரமைப்பு மக்கள் குறைதீர்ப்பு முகாம்கள்.',
    is_active: true
  },
  {
    district_slug: 'madurai',
    district_name: 'Madurai',
    district_name_ta: 'மதுரை',
    mla_name: 'Dr. Palanivel Thiagarajan',
    mla_name_ta: 'முனைவர் பழனிவேல் தியாகராஜன்',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Madurai Central (191)',
    constituency_ta: 'மதுரை மத்தியம் (191)',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/PTR_Palanivel_Thiagarajan.jpg/400px-PTR_Palanivel_Thiagarajan.jpg',
    elected_date: '2021-05-02',
    vote_share: 58.70,
    winning_margin: 34176,
    performance_score: 89,
    key_actions_en: 'Madurai Metro project DPR and route planning monitoring.\nKalaignar Memorial Centenary Library infrastructure and tech hub.\nVadapalanji IT Park job creation and tech startup incubation.',
    key_actions_ta: 'மதுரை மெட்ரோ ரயில் திட்ட விரிவான திட்ட அறிக்கை (DPR) கண்காணிப்பு.\nகலைஞர் நூற்றாண்டு நூலக நவீன உட்கட்டமைப்பு மற்றும் தொழில் மையம்.\nவடபழஞ்சி தகவல் தொழில்நுட்ப பூங்கா முதலீடுகள் ஈர்ப்பு.',
    is_active: true
  },
  {
    district_slug: 'tiruchirappalli',
    district_name: 'Tiruchirappalli',
    district_name_ta: 'திருச்சிராப்பள்ளி',
    mla_name: 'K. N. Nehru',
    mla_name_ta: 'கே. என். நேரு',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Tiruchirappalli West (140)',
    constituency_ta: 'திருச்சிராப்பள்ளி மேற்கு (140)',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Nehru_in_an_public_meeting.jpg/400px-Nehru_in_an_public_meeting.jpg',
    elected_date: '2021-05-02',
    vote_share: 64.52,
    winning_margin: 85109,
    performance_score: 88,
    key_actions_en: 'Panjapur integrated mega bus terminus construction.\nElevated highway corridor connecting Trichy Head Post Office to Chathiram.\nUyyakondan canal bund greening and flood diversion channel.',
    key_actions_ta: 'பஞ்சப்பூர் ஒருங்கிணைந்த பேருந்து முனையம் அமைக்கும் பணி.\nதலைமை தபால் நிலையம் முதல் சத்திரம் பேருந்து நிலையம் வரையிலான உயர்மட்ட பாலம்.\nஉய்யக்கொண்டான் கால்வாய் சீரமைப்பு மற்றும் வெள்ளத் தடுப்புப் பணிகள்.',
    is_active: true
  },
  {
    district_slug: 'tirunelveli',
    district_name: 'Tirunelveli',
    district_name_ta: 'திருநெல்வேலி',
    mla_name: 'Nainar Nagendran',
    mla_name_ta: 'நயினார் நாகேந்திரன்',
    party_slug: 'bjp',
    party_name: 'BJP',
    constituency: 'Tirunelveli (224)',
    constituency_ta: 'திருநெல்வேலி (224)',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Nainar_Nagendran.jpg/400px-Nainar_Nagendran.jpg',
    elected_date: '2021-05-02',
    vote_share: 46.70,
    winning_margin: 23107,
    performance_score: 80,
    key_actions_en: 'Thamirabarani river sewage prevention and desilting project.\nTirunelveli Junction railway terminal platform upgrades.\nNellai weavers and palm jaggery cooperative grievance representations.',
    key_actions_ta: 'தாமிரபரணி நதி கழிவுநீர் கலப்பு தடுப்பு மற்றும் தூர்வாரும் பணிகள்.\nதிருநெல்வேலி சந்திப்பு ரயில் நிலைய கூடுதல் முனையப் பணிகள்.\nநெல்லை நெசவாளர்கள் மற்றும் பனை விவசாயிகளுக்கான உதவித்திட்ட நடவடிக்கைகள்.',
    is_active: true
  },
  {
    district_slug: 'thoothukudi',
    district_name: 'Thoothukudi',
    district_name_ta: 'தூத்துக்குடி',
    mla_name: 'P. Geetha Jeevan',
    mla_name_ta: 'கீதா ஜீவன்',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Thoothukudi (215)',
    constituency_ta: 'தூத்துக்குடி (215)',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Geetha_Jeevan.jpg/400px-Geetha_Jeevan.jpg',
    elected_date: '2021-05-02',
    vote_share: 57.58,
    winning_margin: 50310,
    performance_score: 85,
    key_actions_en: 'Corporation storm water pump stations and flood mitigation.\nSalt pan worker monsoonal welfare relief distribution.\nV.O.C. Port industrial corridor development and employment camps.',
    key_actions_ta: 'தூத்துக்குடி மாநகராட்சி மழைநீர் வடிகால் பம்பிங் நிலையங்கள் அமைப்பு.\nஉப்பளத் தொழிலாளர்களுக்கு மழைக்கால நிவாரண நிதி விநியோகம்.\nவ.உ.சி துறைமுக தொழிற்பேட்டை வேலைவாய்ப்பு முகாம்கள்.',
    is_active: true
  },
  {
    district_slug: 'tiruvannamalai',
    district_name: 'Tiruvannamalai',
    district_name_ta: 'திருவண்ணாமலை',
    mla_name: 'E. V. Velu',
    mla_name_ta: 'எ. வ. வேலு',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Tiruvannamalai (063)',
    constituency_ta: 'திருவண்ணாமலை (063)',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/E_V_Velu.jpg/400px-E_V_Velu.jpg',
    elected_date: '2021-05-02',
    vote_share: 61.64,
    winning_margin: 94673,
    performance_score: 87,
    key_actions_en: 'Girivalam path pedestrian safety, solar lighting, and pilgrim amenities.\nTiruvannamalai outer ring road project completion.\nDistrict arterial highways four-laning and bridge reconstruction.',
    key_actions_ta: 'கிரிவலப் பாதை நடைபயிற்சி பாதுகாப்பு, சோலார் விளக்குகள் மற்றும் பக்தர்களுக்கான வசதிகள்.\nதிருவண்ணாமலை வெளிவட்டச் சாலைப் பணிகள் நிறைவு.\nமாவட்ட நெடுஞ்சாலைகள் நான்கு வழிச்சாலை மற்றும் புதிய பாலங்கள் கட்டுதல்.',
    is_active: true
  },
  {
    district_slug: 'erode',
    district_name: 'Erode',
    district_name_ta: 'ஈரோடு',
    mla_name: 'E. V. K. S. Elangovan',
    mla_name_ta: 'ஈ. வி. கே. எஸ். இளங்கோவன்',
    party_slug: 'inc',
    party_name: 'INC',
    constituency: 'Erode East (098)',
    constituency_ta: 'ஈரோடு கிழக்கு (098)',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/EVKS_Elangovan.jpg/400px-EVKS_Elangovan.jpg',
    elected_date: '2023-03-02',
    vote_share: 64.58,
    winning_margin: 66233,
    performance_score: 82,
    key_actions_en: 'Zero-liquid discharge common effluent treatment plant for textile units.\nPerumpallam canal revival and concrete revetment wall.\nNethaji daily market modern trade complex commissioning.',
    key_actions_ta: 'ஜவுளி ஆலைகளுக்கான பொது கழிவுநீர் சுத்திகரிப்பு ஆலை நவீனமயமாக்கல்.\nபெரும்பள்ளம் ஓடை தூர்வாருதல் மற்றும் கான்கிரீட் தடுப்புச்சுவர்.\nநேதாஜி காய்கறி தினசரி சந்தை நவீன வளாகம் பயன்பாட்டிற்கு கொண்டு வருதல்.',
    is_active: true
  },
  {
    district_slug: 'karur',
    district_name: 'Karur',
    district_name_ta: 'கரூர்',
    mla_name: 'V. Senthilbalaji',
    mla_name_ta: 'வி. செந்தில்பாலாஜி',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Karur (135)',
    constituency_ta: 'கரூர் (135)',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/V._Senthil_Balaji.jpg/400px-V._Senthil_Balaji.jpg',
    elected_date: '2021-05-02',
    vote_share: 49.33,
    winning_margin: 12448,
    performance_score: 84,
    key_actions_en: 'Mayanur barrage water regulation and irrigation canal lining.\nKarur textile export park infrastructure.\nAmaravathi river bank protection retaining wall.',
    key_actions_ta: 'மாயனூர் கதவணை நீர் ஒழுங்குமுறை மற்றும் பாசன வாய்க்கால் சீரமைப்பு.\nகரூர் ஜவுளி ஏற்றுமதி பூங்கா கட்டமைப்பு மேம்பாடுகள்.\nஅமராவதி ஆற்றுப்படுகை தடுப்புச்சுவர் அமைக்கும் பணிகள்.',
    is_active: true
  },
  {
    district_slug: 'ranipet',
    district_name: 'Ranipet',
    district_name_ta: 'ராணிப்பேட்டை',
    mla_name: 'R. Gandhi',
    mla_name_ta: 'ஆர். காந்தி',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Ranipet (041)',
    constituency_ta: 'ராணிப்பேட்டை (041)',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/R_Gandhi_Minister.jpg/400px-R_Gandhi_Minister.jpg',
    elected_date: '2021-05-02',
    vote_share: 49.79,
    winning_margin: 16498,
    performance_score: 85,
    key_actions_en: 'New Ranipet District Collectorate complex inauguration.\nSIPCOT leather industrial effluent treatment modernization.\nPalar check dam construction for groundwater recharge.',
    key_actions_ta: 'ராணிப்பேட்டை புதிய மாவட்ட ஆட்சியர் பெருந்திட்ட வளாகம் திறப்பு.\nசிப்காட் தோல் பதனிடும் கழிவுநீர் சுத்திகரிப்பு நவீனமயமாக்கல்.\nபாலாறு தடுப்பணைகள் மூலம் நிலத்தடி நீர்மட்டம் உயர்த்துதல்.',
    is_active: true
  },
  {
    district_slug: 'theni',
    district_name: 'Theni',
    district_name_ta: 'தேனி',
    mla_name: 'O. Panneerselvam',
    mla_name_ta: 'ஓ. பன்னீர்செல்வம்',
    party_slug: 'independent',
    party_name: 'Independent',
    constituency: 'Bodinayakanur (199)',
    constituency_ta: 'போடிநாயக்கனூர் (199)',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/O._Panneerselvam.jpg/400px-O._Panneerselvam.jpg',
    elected_date: '2021-05-02',
    vote_share: 46.56,
    winning_margin: 11021,
    performance_score: 79,
    key_actions_en: 'Mullaperiyar dam water storage maintenance advocacy.\nCardamom and tea planter transport subsidy follow-ups.\n18th canal irrigation water supply release representations.',
    key_actions_ta: 'முல்லைப்பெரியாறு அணை நீர்மட்ட உரிமைகள் குறித்த சட்டசபைக் குரல்.\nஏலக்காய் மற்றும் தேயிலை விவசாயிகள் போக்குவரத்து நிவாரண முயற்சிகள்.\n18-ம் கால்வாய் பாசன நீர் திறப்பு கோரிக்கைகள்.',
    is_active: true
  },
  {
    district_slug: 'nagapattinam',
    district_name: 'Nagapattinam',
    district_name_ta: 'நாகப்பட்டினம்',
    mla_name: 'Aloor Shanavas',
    mla_name_ta: 'ஆளூர் ஷாநவாஸ்',
    party_slug: 'vck',
    party_name: 'VCK',
    constituency: 'Nagapattinam (163)',
    constituency_ta: 'நாகப்பட்டினம் (163)',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Aloor_Shanavas.jpg/400px-Aloor_Shanavas.jpg',
    elected_date: '2021-05-02',
    vote_share: 46.23,
    winning_margin: 7238,
    performance_score: 83,
    key_actions_en: 'Nagapattinam-Kankesanthurai international ferry service connectivity.\nCoastal protection sea wall construction in vulnerable fishing hamlets.\nFishermen high-seas satellite tracker & communication drives.',
    key_actions_ta: 'நாகப்பட்டினம் - காங்கேசன்துறை சர்வதேச பயணிகள் கப்பல் போக்குவரத்து முயற்சிகள்.\nமீனவ கிராமங்களில் கடல் அரிப்பு தடுப்பு சுவர் அமைத்தல்.\nஆழ்கடல் மீனவர்களுக்கு செயற்கைக்கோள் தகவல் தொடர்பு உபகரணங்கள் வழங்கல்.',
    is_active: true
  },
  {
    district_slug: 'kanniyakumari',
    district_name: 'Kanniyakumari',
    district_name_ta: 'கன்னியாகுமரி',
    mla_name: 'M. R. Gandhi',
    mla_name_ta: 'எம். ஆர். காந்தி',
    party_slug: 'bjp',
    party_name: 'BJP',
    constituency: 'Nagercoil (230)',
    constituency_ta: 'நாகர்கோவில் (230)',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/M._R._Gandhi.jpg/400px-M._R._Gandhi.jpg',
    elected_date: '2021-05-02',
    vote_share: 48.21,
    winning_margin: 11669,
    performance_score: 79,
    key_actions_en: 'Four-lane highway works monitoring connecting Nagercoil to Trivandrum.\nRubber and coconut MSP farmer welfare representations.\nColachel fishing harbor infrastructural expansion.',
    key_actions_ta: 'நாகர்கோவில் - திருவனந்தபுரம் நான்கு வழிச்சாலை பணிகளை விரைவுபடுத்துதல்.\nரப்பர் மற்றும் தென்னை விவசாயிகளுக்கு நியாயமான குறைந்தபட்ச ஆதார விலை கோரிக்கை.\nகுளச்சல் மீன்பிடி துறைமுக உள்கட்டமைப்பு விரிவாக்கம்.',
    is_active: true
  },
  {
    district_slug: 'dindigul',
    district_name: 'Dindigul',
    district_name_ta: 'திண்டுக்கல்',
    mla_name: 'Dindigul C. Sreenivasan',
    mla_name_ta: 'திண்டுக்கல் சி. சீனிவாசன்',
    party_slug: 'aiadmk',
    party_name: 'AIADMK',
    constituency: 'Dindigul (127)',
    constituency_ta: 'திண்டுக்கல் (127)',
    photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Dindigul_C._Sreenivasan.jpg/400px-Dindigul_C._Sreenivasan.jpg',
    elected_date: '2021-05-02',
    vote_share: 46.90,
    winning_margin: 17797,
    performance_score: 78,
    key_actions_en: 'Lock industry and brassware artisan welfare representations.\nAthoor Kamarajar Sagar dam drinking water pipeline monitoring.\nSirumalai tourist hill road maintenance petition.',
    key_actions_ta: 'திண்டுக்கல் பூட்டு மற்றும் பித்தளை தொழிலாளர்களுக்கு நலவாரிய சலுகைகள் கோரிக்கை.\nஆத்தூர் காமராஜர் நீர்த்தேக்க குடிநீர் குழாய் பராமரிப்பு.\nசிறுமலை சுற்றுலா மலைப்பாதை சீரமைப்பு மனு.',
    is_active: true
  },
  {
    district_slug: 'vellore',
    district_name: 'Vellore',
    district_name_ta: 'வேலூர்',
    mla_name: 'P. Karthikeyan',
    mla_name_ta: 'ப. கார்த்திகேயன்',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Vellore (043)',
    constituency_ta: 'வேலூர் (043)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/043.jpg',
    elected_date: '2021-05-02',
    vote_share: 46.86,
    winning_margin: 9181,
    performance_score: 80,
    key_actions_en: 'Vellore Abdullapuram airport launch follow-up.\nPalar check dam maintenance across Vellore limits.\nOtteri lake rejuvenation and park amenities.',
    key_actions_ta: 'வேலூர் அப்துல்லாபுரம் விமான நிலைய பணிகள் துரிதப்படுத்துதல்.\nவேலூர் எல்லை பாலாறு தடுப்பணை பராமரிப்பு.\nஒட்டேரி ஏரி புனரமைப்பு மற்றும் பூங்கா வசதிகள்.',
    is_active: true
  },
  {
    district_slug: 'thanjavur',
    district_name: 'Thanjavur',
    district_name_ta: 'தஞ்சாவூர்',
    mla_name: 'T. K. G. Neelamegam',
    mla_name_ta: 'டி. கே. ஜி. நீலமேகம்',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Thanjavur (174)',
    constituency_ta: 'தஞ்சாவூர் (174)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/174.jpg',
    elected_date: '2021-05-02',
    vote_share: 53.25,
    winning_margin: 47449,
    performance_score: 83,
    key_actions_en: 'Grand Anicut canal desilting and water release schedule.\nDirect Paddy Procurement Centers (DPC) moisture limit relaxation.\nThanjavur Smart City heritage moat restoration.',
    key_actions_ta: 'கல்லணை கால்வாய் தூர்வாருதல் மற்றும் நீர் ஒழுங்குமுறை.\nநேரடி நெல் கொள்முதல் நிலையங்களில் (DPC) ஈரப்பத தளர்வு கோரிக்கை.\nதஞ்சை ஸ்மார்ட் சிட்டி அகழி புனரமைப்பு.',
    is_active: true
  },
  {
    district_slug: 'kancheepuram',
    district_name: 'Kancheepuram',
    district_name_ta: 'காஞ்சிபுரம்',
    mla_name: 'C. V. M. P. Ezhilarasan',
    mla_name_ta: 'சி. வி. எம். பி. எழிலரசன்',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Kancheepuram (037)',
    constituency_ta: 'காஞ்சிபுரம் (037)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/037.jpg',
    elected_date: '2021-05-02',
    vote_share: 44.77,
    winning_margin: 11595,
    performance_score: 82,
    key_actions_en: 'Silk weavers raw silk subsidy distribution and welfare boards.\nVegavathi river rejuvenation and encroachment clearance.\nTemple town ring road and pilgrim parking facilities.',
    key_actions_ta: 'பட்டு நெசவாளர்களுக்கு மானிய விலை கச்சா பட்டு விநியோகம்.\nவேகவதி நதி தூர்வாருதல் மற்றும் ஆக்கிரமிப்பு அகற்றம்.\nகோயில் நகர சுற்றுவட்டச் சாலை மற்றும் வாகன நிறுத்துமிடம்.',
    is_active: true
  },
  {
    district_slug: 'namakkal',
    district_name: 'Namakkal',
    district_name_ta: 'நாமக்கல்',
    mla_name: 'P. Ramalingam',
    mla_name_ta: 'பெ. ராமலிங்கம்',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Namakkal (095)',
    constituency_ta: 'நாமக்கல் (095)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/095.jpg',
    elected_date: '2021-05-02',
    vote_share: 51.52,
    winning_margin: 27861,
    performance_score: 81,
    key_actions_en: 'Poultry industry feed price subsidy representations.\nLorry body building industrial cluster amenities.\nMohanur railway overbridge construction.',
    key_actions_ta: 'கோழிப்பண்ணை தீவன விலை மானிய கோரிக்கை.\nலாரி கூண்டு கட்டும் தொழில் கூட்டமைப்பு அடிப்படை வசதிகள்.\nமோகனூர் ரயில்வே மேம்பாலம் அமைக்கும் பணி.',
    is_active: true
  },
  {
    district_slug: 'nilgiris',
    district_name: 'Nilgiris',
    district_name_ta: 'நீலகிரி',
    mla_name: 'R. Ganesh',
    mla_name_ta: 'ஆர். கணேஷ்',
    party_slug: 'inc',
    party_name: 'INC',
    constituency: 'Udhagamandalam (108)',
    constituency_ta: 'உதகமண்டலம் (108)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/108.jpg',
    elected_date: '2021-05-02',
    vote_share: 46.90,
    winning_margin: 5348,
    performance_score: 79,
    key_actions_en: 'Small tea growers green leaf minimum floor price guarantee.\nHuman-wildlife conflict rapid response squad enhancement.\nOoty heritage mountain railway route protection.',
    key_actions_ta: 'சிறு தேயிலை விவசாயிகளுக்கு பசுந்தேயிலை நியாய விலை உத்தரவாதம்.\nமனித-விலங்கு மோதல் தடுப்பு விரைவுப் படை பலப்படுத்துதல்.\nஊட்டி பாரம்பரிய மலை ரயில் பாதை பாதுகாப்பு.',
    is_active: true
  },
  {
    district_slug: 'perambalur',
    district_name: 'Perambalur',
    district_name_ta: 'பெரம்பலூர்',
    mla_name: 'M. Prabhakaran',
    mla_name_ta: 'எம். பிரபாகரன்',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Perambalur (SC) (147)',
    constituency_ta: 'பெரம்பலூர் (SC) (147)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/147.jpg',
    elected_date: '2021-05-02',
    vote_share: 48.06,
    winning_margin: 12177,
    performance_score: 80,
    key_actions_en: 'Small onion cold storage warehouse network.\nSIPCOT Padalur industrial estate employment creation.\nDrinking water pipeline distribution across drought-prone blocks.',
    key_actions_ta: 'சின்ன வெங்காயம் குளிர்பதன கிடங்கு வசதிகள் அமைத்தல்.\nசிப்காட் பாடாலூர் தொழிற்பேட்டை வேலைவாய்ப்பு முகாம்கள்.\nவறட்சி பாதித்த ஒன்றியங்களில் குடிநீர் குழாய் திட்டங்கள்.',
    is_active: true
  },
  {
    district_slug: 'pudukkottai',
    district_name: 'Pudukkottai',
    district_name_ta: 'புதுக்கோட்டை',
    mla_name: 'Dr. V. Muthuraja',
    mla_name_ta: 'மருத்துவர் வி. முத்துராஜா',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Pudukkottai (180)',
    constituency_ta: 'புதுக்கோட்டை (180)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/180.jpg',
    elected_date: '2021-05-02',
    vote_share: 44.42,
    winning_margin: 12998,
    performance_score: 81,
    key_actions_en: 'Government Medical College Hospital cardiology unit upgrades.\nCauvery-Gundar river linking scheme monitoring in Pudukkottai section.\nMachuvadi railway gate overbridge work completion.',
    key_actions_ta: 'அரசு மருத்துவக் கல்லூரி மருத்துவமனை இருதய பிரிவு நவீனமயமாக்கல்.\nகாவிரி-குண்டாறு இணைப்பு கால்வாய் திட்டப் பணிகள் மேற்பார்வை.\nமச்சுவாடி ரயில்வே கேட் மேம்பால பணிகள் நிறைவு.',
    is_active: true
  },
  {
    district_slug: 'ramanathapuram',
    district_name: 'Ramanathapuram',
    district_name_ta: 'இராமநாதபுரம்',
    mla_name: 'Katharbatcha Muthuramalingam',
    mla_name_ta: 'காதர்பாட்ஷா முத்துராமலிங்கம்',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Ramanathapuram (211)',
    constituency_ta: 'இராமநாதபுரம் (211)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/211.jpg',
    elected_date: '2021-05-02',
    vote_share: 51.88,
    winning_margin: 50479,
    performance_score: 82,
    key_actions_en: 'Seawater desalination plant drinking water scheme expansion.\nRamanathapuram chilli (Gundu Milagai) GI tag farmer promotion.\nRameshwaram pilgrimage road and sanitation infrastructure.',
    key_actions_ta: 'கடல்நீரை குடிநீராக்கும் திட்ட விரிவாக்கம்.\nராமநாதபுரம் குண்டு மிளகாய் விவசாயிகளுக்கு ஏற்றுமதி சந்தை வசதிகள்.\nராமேஸ்வரம் புனித யாத்திரை சாலை மற்றும் சுகாதார வசதிகள்.',
    is_active: true
  },
  {
    district_slug: 'sivaganga',
    district_name: 'Sivaganga',
    district_name_ta: 'சிவகங்கை',
    mla_name: 'P. R. Senthilnathan',
    mla_name_ta: 'பி. ஆர். செந்தில்நாதன்',
    party_slug: 'aiadmk',
    party_name: 'AIADMK',
    constituency: 'Sivaganga (184)',
    constituency_ta: 'சிவகங்கை (184)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/184.jpg',
    elected_date: '2021-05-02',
    vote_share: 45.41,
    winning_margin: 9253,
    performance_score: 79,
    key_actions_en: 'Keeladi archaeology center infrastructure and transport connectivity.\nVaigai surplus water supply for Sivaganga irrigation tanks.\nDistrict hospital emergency trauma care equipment.',
    key_actions_ta: 'கீழடி தொல்லியல் அருங்காட்சியக போக்குவரத்து வசதிகள்.\nவைகை உபரி நீர் சிவகங்கை கண்மாய்களுக்கு திருப்பி விடுதல்.\nமாவட்ட மருத்துவமனை அவசர சிகிச்சை பிரிவு மேம்பாடு.',
    is_active: true
  },
  {
    district_slug: 'tenkasi',
    district_name: 'Tenkasi',
    district_name_ta: 'தென்காசி',
    mla_name: 'S. Palani Nadar',
    mla_name_ta: 'எஸ். பழனி நாடார்',
    party_slug: 'inc',
    party_name: 'INC',
    constituency: 'Tenkasi (222)',
    constituency_ta: 'தென்காசி (222)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/222.jpg',
    elected_date: '2021-05-02',
    vote_share: 41.97,
    winning_margin: 370,
    performance_score: 80,
    key_actions_en: 'Courtallam waterfalls tourist amenities and safety renovations.\nTenkasi-Tirunelveli railway electrification and track doubling.\nHorticulture lemon and mango farmers marketing support.',
    key_actions_ta: 'குற்றால அருவிகள் சுற்றுலா பயணிகள் வசதிகள் மற்றும் பாதுகாப்பு மேம்பாடு.\nதென்காசி - நெல்லை ரயில் மின்மயமாக்கல் பணிகள்.\nஎலுமிச்சை மற்றும் மாம்பழ விவசாயிகளுக்கு நேரடி விற்பனை மையம்.',
    is_active: true
  },
  {
    district_slug: 'tiruppur',
    district_name: 'Tiruppur',
    district_name_ta: 'திருப்பூர்',
    mla_name: 'K. Selvaraj',
    mla_name_ta: 'க. செல்வராஜ்',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Tiruppur South (114)',
    constituency_ta: 'திருப்பூர் தெற்கு (114)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/114.jpg',
    elected_date: '2021-05-02',
    vote_share: 43.68,
    winning_margin: 4709,
    performance_score: 81,
    key_actions_en: 'Knitwear export MSME yarn price stability representation.\nTiruppur 4th dedicated drinking water pipeline supply.\nNoyyal river pollution remediation and bio-mining of old dump yards.',
    key_actions_ta: 'பின்னலாடை சிறு-குறு தொழில் நூல் விலை நிலைத்தன்மை கோரிக்கை.\nதிருப்பூர் 4-வது கூட்டுக் குடிநீர் திட்ட விரைவு விநியோகம்.\nநொய்யல் நதி கழிவு அகற்றம் மற்றும் குப்பை கிடங்கு பயோ-மைனிங்.',
    is_active: true
  },
  {
    district_slug: 'tiruvallur',
    district_name: 'Tiruvallur',
    district_name_ta: 'திருவள்ளூர்',
    mla_name: 'V. G. Raajendran',
    mla_name_ta: 'வி. ஜி. ராஜேந்திரன்',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Tiruvallur (004)',
    constituency_ta: 'திருவள்ளூர் (004)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/004.jpg',
    elected_date: '2021-05-02',
    vote_share: 50.27,
    winning_margin: 22701,
    performance_score: 83,
    key_actions_en: 'Tiruvallur Government Medical College and Hospital full commissioning.\nChennai suburban rail corridor punctuality and additional fast locals.\nCooum river pollution cleanup at Kesavaram barrage.',
    key_actions_ta: 'திருவள்ளூர் அரசு மருத்துவக் கல்லூரி முழு செயல்பாட்டிற்கு கொண்டு வருதல்.\nசென்னை புறநகர் மின்சார ரயில்கள் காலநேர இயக்கம் உறுதி செய்தல்.\nகூவம் நதி கேசவரம் தடுப்பணை கழிவுநீர் சுத்திகரிப்பு.',
    is_active: true
  },
  {
    district_slug: 'tiruvarur',
    district_name: 'Tiruvarur',
    district_name_ta: 'திருவாரூர்',
    mla_name: 'K. Poondi Kalaivanan',
    mla_name_ta: 'பூண்டி கே. கலைவாணன்',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Tiruvarur (168)',
    constituency_ta: 'திருவாரூர் (168)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/168.jpg',
    elected_date: '2021-05-02',
    vote_share: 52.29,
    winning_margin: 51174,
    performance_score: 82,
    key_actions_en: 'Central University of Tamil Nadu (CUTN) arterial road connectivity.\nVennar and Vettar river irrigation delta modernization.\nPaddy procurement center infrastructure with moisture dryers.',
    key_actions_ta: 'தமிழ்நாடு மத்திய பல்கலைக்கழக இணைப்புச் சாலை வசதிகள்.\nவெண்ணாறு மற்றும் வெட்டாறு பாசன வாய்க்கால்கள் நவீனமயமாக்கல்.\nநெல் கொள்முதல் நிலையங்களில் நவீன உலர் களங்கள் அமைத்தல்.',
    is_active: true
  },
  {
    district_slug: 'villupuram',
    district_name: 'Villupuram',
    district_name_ta: 'விழுப்புரம்',
    mla_name: 'R. Lakshmanan',
    mla_name_ta: 'ஆர். லட்சுமணன்',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Villupuram (074)',
    constituency_ta: 'விழுப்புரம் (074)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/074.jpg',
    elected_date: '2021-05-02',
    vote_share: 47.78,
    winning_margin: 14868,
    performance_score: 81,
    key_actions_en: 'Villupuram municipality underground drainage phase-2 completion.\nSugarcane farmers mill arrears settlement drives.\nNew Villupuram master bus terminal project.',
    key_actions_ta: 'விழுப்புரம் பாதாள சாக்கடை 2-ம் கட்ட பணிகள் நிறைவு.\nகரும்பு விவசாயிகளுக்கு ஆலை நிலுவைத் தொகை பட்டுவாடா.\nவிழுப்புரம் புதிய ஒருங்கிணைந்த பேருந்து நிலைய பணிகள்.',
    is_active: true
  },
  {
    district_slug: 'virudhunagar',
    district_name: 'Virudhunagar',
    district_name_ta: 'விருதுநகர்',
    mla_name: 'A. R. R. Seenivasan',
    mla_name_ta: 'ஏ. ஆர். ஆர். சீனிவாசன்',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Virudhunagar (206)',
    constituency_ta: 'விருதுநகர் (206)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/206.jpg',
    elected_date: '2021-05-02',
    vote_share: 44.02,
    winning_margin: 21339,
    performance_score: 82,
    key_actions_en: 'Fireworks safety certification and green cracker transition mission.\nEdible oil and pulse processing trade center infrastructure.\nKowsiga river check dam construction for water table recovery.',
    key_actions_ta: 'பட்டாசு தொழில் பாதுகாப்பு மற்றும் பசுமை பட்டாசு தொழில்நுட்ப உதவி.\nஎண்ணெய் மற்றும் பருப்பு ஆலைகள் வர்த்தக மையம்.\nகௌசிகா ஆற்று தடுப்பணை கட்டி நிலத்தடி நீர்மட்டம் உயர்த்துதல்.',
    is_active: true
  },
  {
    district_slug: 'ariyalur',
    district_name: 'Ariyalur',
    district_name_ta: 'அரியலூர்',
    mla_name: 'K. Chinnappa',
    mla_name_ta: 'கு. சின்னப்பா',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Ariyalur (149)',
    constituency_ta: 'அரியலூர் (149)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/149.jpg',
    elected_date: '2021-05-02',
    vote_share: 50.54,
    winning_margin: 3234,
    performance_score: 79,
    key_actions_en: 'Ariyalur bypass bypass road construction and railway overbridge.\nCashew and groundnut farmer MSP grievance settlement.\nDrinking water supply coverage in cement factory surrounding villages.',
    key_actions_ta: 'அரியலூர் புறவழிச்சாலை மற்றும் ரயில்வே மேம்பாலம் அமைத்தல்.\nமுந்திரி மற்றும் நிலக்கடலை விவசாயிகளுக்கு நேரடி கொள்முதல் மையம்.\nசிமெண்ட் ஆலை சுற்றியுள்ள கிராமங்களுக்கு பாதுகாக்கப்பட்ட குடிநீர் வழங்கல்.',
    is_active: true
  },
  {
    district_slug: 'chengalpattu',
    district_name: 'Chengalpattu',
    district_name_ta: 'செங்கல்பட்டு',
    mla_name: 'M. Varalakshmi',
    mla_name_ta: 'எம். வரலட்சுமி',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Chengalpattu (032)',
    constituency_ta: 'செங்கல்பட்டு (032)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/032.jpg',
    elected_date: '2021-05-02',
    vote_share: 49.32,
    winning_margin: 26665,
    performance_score: 83,
    key_actions_en: 'GST road traffic congestion decongestion and elevated corridor works.\nKolavai lake eco-restoration and desilting project.\nChennai-Chengalpattu suburban train frequency enhancement.',
    key_actions_ta: 'ஜிஎஸ்டி சாலை போக்குவரத்து நெரிசல் தீர்வு மற்றும் உயர்மட்ட சாலை பணிகள்.\nகொளவை ஏரி தூர்வாருதல் மற்றும் சூழலியல் மறுசீரமைப்பு.\nசென்னை - செங்கல்பட்டு புறநகர் மின்சார ரயில் சேவை அதிகரிப்பு.',
    is_active: true
  },
  {
    district_slug: 'cuddalore',
    district_name: 'Cuddalore',
    district_name_ta: 'கடலூர்',
    mla_name: 'G. Iyappan',
    mla_name_ta: 'கோ. ஐயப்பன்',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Cuddalore (153)',
    constituency_ta: 'கடலூர் (153)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/153.jpg',
    elected_date: '2021-05-02',
    vote_share: 46.45,
    winning_margin: 5151,
    performance_score: 81,
    key_actions_en: 'Cuddalore commercial port expansion follow-up.\nSIPCOT industrial air and water emission monitoring unit.\nCoastal tsunami relief colony civic amenity revamps.',
    key_actions_ta: 'கடலூர் வணிகத் துறைமுக விரிவாக்கப் பணிகள் மேற்பார்வை.\nசிப்காட் தொழிற்சாலை மாசு கட்டுப்பாடு கண்காணிப்பு மையம்.\nகடற்கரை சுனாமி குடியிருப்புகளில் அடிப்படை வசதிகள் சீரமைப்பு.',
    is_active: true
  },
  {
    district_slug: 'dharmapuri',
    district_name: 'Dharmapuri',
    district_name_ta: 'தர்மபுரி',
    mla_name: 'S. P. Venkateshwaran',
    mla_name_ta: 'எஸ். பி. வெங்கடேஸ்வரன்',
    party_slug: 'pmk',
    party_name: 'PMK',
    constituency: 'Dharmapuri (084)',
    constituency_ta: 'தர்மபுரி (084)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/084.jpg',
    elected_date: '2021-05-02',
    vote_share: 48.71,
    winning_margin: 26860,
    performance_score: 80,
    key_actions_en: 'Cauvery surplus water diversion to Dharmapuri lakes advocacy.\nMorappur-Dharmapuri railway line land acquisition speedup.\nMango processing export center setup in Dharmapuri.',
    key_actions_ta: 'காவிரி உபரி நீர் தர்மபுரி ஏரிகளுக்கு கொண்டு வரும் திட்டம் வலியுறுத்தல்.\nமொரப்பூர் - தர்மபுரி ரயில்வே இணைப்பு நில எடுப்பு விரைவுபடுத்துதல்.\nதர்மபுரியில் மாம்பழ கூழ் பதப்படுத்தும் ஏற்றுமதி மையம் அமைத்தல்.',
    is_active: true
  },
  {
    district_slug: 'kallakurichi',
    district_name: 'Kallakurichi',
    district_name_ta: 'கள்ளக்குறிச்சி',
    mla_name: 'M. Senthilkumar',
    mla_name_ta: 'மா. செந்தில்குமார்',
    party_slug: 'aiadmk',
    party_name: 'AIADMK',
    constituency: 'Kallakurichi (SC) (080)',
    constituency_ta: 'கள்ளக்குறிச்சி (SC) (080)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/080.jpg',
    elected_date: '2021-05-02',
    vote_share: 48.97,
    winning_margin: 25891,
    performance_score: 79,
    key_actions_en: 'Gomukhi dam irrigation canal water release management.\nDistrict Headquarters hospital specialty trauma ward operations.\nAgricultural 24x7 3-phase electricity distribution follow-up.',
    key_actions_ta: 'கோமுகி அணை பாசன வாய்க்கால் நீர் பங்கீடு மேற்பார்வை.\nமாவட்ட தலைமை மருத்துவமனை அவசர சிகிச்சை பிரிவு செயல்பாடுகள்.\nவிவசாயிகளுக்கு தடையில்லா மும்முனை மின்சாரம் உறுதி செய்தல்.',
    is_active: true
  },
  {
    district_slug: 'krishnagiri',
    district_name: 'Krishnagiri',
    district_name_ta: 'கிருஷ்ணகிரி',
    mla_name: 'K. Ashok Kumar',
    mla_name_ta: 'கே. அசோக் குமார்',
    party_slug: 'aiadmk',
    party_name: 'AIADMK',
    constituency: 'Krishnagiri (053)',
    constituency_ta: 'கிருஷ்ணகிரி (053)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/053.jpg',
    elected_date: '2021-05-02',
    vote_share: 44.82,
    winning_margin: 794,
    performance_score: 78,
    key_actions_en: 'Kelavarapalli dam water quality cleanup from foam and industrial waste.\nKrishnagiri mango cluster export incentives.\nKrishnagiri town ring road land acquisition monitoring.',
    key_actions_ta: 'கெலவரப்பள்ளி அணை ரசாயன நுரை கழிவுநீர் தூய்மைப்படுத்தும் பணி.\nகிருஷ்ணகிரி மாம்பழ விவசாயிகளுக்கு ஏற்றுமதி மானியம்.\nகிருஷ்ணகிரி நகர புறவழிச்சாலை நில எடுப்பு பணிகள்.',
    is_active: true
  },
  {
    district_slug: 'mayiladuthurai',
    district_name: 'Mayiladuthurai',
    district_name_ta: 'மயிலாடுதுறை',
    mla_name: 'S. Rajakumar',
    mla_name_ta: 'எஸ். ராஜகுமார்',
    party_slug: 'inc',
    party_name: 'INC',
    constituency: 'Mayiladuthurai (160)',
    constituency_ta: 'மயிலாடுதுறை (160)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/160.jpg',
    elected_date: '2021-05-02',
    vote_share: 42.12,
    winning_margin: 2746,
    performance_score: 80,
    key_actions_en: 'New Mayiladuthurai District Collectorate master building setup.\nCauvery delta tail-end irrigation canal desilting.\nPoompuhar harbor sea wall protection and tourism development.',
    key_actions_ta: 'புதிய மயிலாடுதுறை மாவட்ட ஆட்சியர் பெருந்திட்ட வளாகப் பணிகள்.\nகாவிரி டெல்டா கடைமடை பாசன வாய்க்கால்கள் தூர்வாருதல்.\nபூம்புகார் துறைமுக கடல் அரிப்பு தடுப்பு மற்றும் சுற்றுலா மேம்பாடு.',
    is_active: true
  },
  {
    district_slug: 'tirupattur',
    district_name: 'Tirupattur',
    district_name_ta: 'திருப்பத்தூர்',
    mla_name: 'A. Nallathambi',
    mla_name_ta: 'அ. நல்லதம்பி',
    party_slug: 'dmk',
    party_name: 'DMK',
    constituency: 'Tirupattur (050)',
    constituency_ta: 'திருப்பத்தூர் (050)',
    photo_url: 'https://assembly.tn.gov.in/16thassembly/members/photos/050.jpg',
    elected_date: '2021-05-02',
    vote_share: 51.91,
    winning_margin: 28240,
    performance_score: 82,
    key_actions_en: 'Yelagiri hills tourism infrastructure and ghat road safety.\nTirupattur new District Government Hospital super specialty block.\nLeather tanning artisan skill training and employment drive.',
    key_actions_ta: 'ஏலகிரி மலை சுற்றுலா உட்கட்டமைப்பு மற்றும் கொண்டை ஊசி வளைவு சாலை பாதுகாப்பு.\nதிருப்பத்தூர் மாவட்ட அரசு மருத்துவமனை சிறப்பு சிகிச்சை பிரிவு.\nதோல் தொழில் கைவினைஞர்களுக்கான திறன் மேம்பாட்டு பயிற்சி முகாம்கள்.',
    is_active: true
  }
]

export const MLAS_BY_DISTRICT = TN_MLAS_DATA.reduce((acc, mla) => {
  acc[mla.district_slug] = mla
  return acc
}, {})
