/**
 * Post validator for VizhiTN auto-publish pipeline.
 *
 * Validates each AI-generated post against the strict editorial constitution
 * defined in GEMINI.md before inserting into the Supabase `post` table.
 *
 * Rules enforced:
 *  - status MUST be "active" (never "published")
 *  - category_slug MUST be from the 12 allowed slugs
 *  - post_type MUST be from the 6 allowed values
 *  - urgency_level MUST be from the 4 allowed values
 *  - civic_status MUST be from the 7 allowed values
 *  - Required fields must be non-empty strings
 *  - Slug must be non-empty and URL-safe
 *  - Garbled Tamil (Gemini JSON encoding bug) is detected and cleared
 *    so ensureBilingualPost() can re-translate properly from English
 */

const VALID_CATEGORY_SLUGS = new Set([
  'road-infrastructure',
  'water-sanitation',
  'electricity',
  'transport',
  'government-schemes',
  'public-safety',
  'healthcare',
  'education',
  'agriculture',
  'environment',
  'local-development',
  'general',
]);

const VALID_POST_TYPES = new Set([
  'alert',
  'local_update',
  'complaint',
  'appreciation',
  'discussion',
  'bribe',
]);

const VALID_URGENCY_LEVELS = new Set(['low', 'medium', 'high', 'critical']);

const VALID_CIVIC_STATUSES = new Set([
  'reported',
  'community_verified',
  'complaint_needed',
  'complaint_filed',
  'under_followup',
  'claimed_fixed',
  'citizen_verified_fixed',
]);

const REQUIRED_FIELDS = ['district_slug', 'category_slug', 'post_type', 'title_en', 'content_en', 'slug'];

/**
 * Detects if a Tamil string from Gemini is garbled (encoding corruption).
 *
 * Gemini's responseMimeType:'application/json' can corrupt Tamil Unicode into
 * sequences like "r?r3_?r3r?_?" instead of proper Unicode codepoints.
 * We detect this by checking: if the string claims to be Tamil content but
 * contains fewer than 5% actual Tamil Unicode characters (U+0B80-U+0BFF),
 * it's garbled and should be cleared so ensureBilingualPost() re-translates.
 *
 * @param {string} text
 * @returns {boolean} true if garbled/unusable
 */
function isGarbledTamil(text) {
  if (!text || typeof text !== 'string' || text.trim().length < 5) return false;
  const tamilChars = (text.match(/[\u0B80-\u0BFF]/g) || []).length;
  const totalChars = text.replace(/\s/g, '').length;
  // If less than 5% of the non-space characters are Tamil Unicode, it's garbled
  return totalChars > 10 && (tamilChars / totalChars) < 0.05;
}

/**
 * Validates and sanitizes a single post object generated by the AI.
 *
 * @param {object} post - Raw post object from AI response.
 * @param {number} index - Position in the batch (for error messages).
 * @returns {{ valid: boolean, post?: object, reason?: string }}
 */
export function validatePost(post, index = 0) {
  if (!post || typeof post !== 'object') {
    return { valid: false, reason: `[${index}] Not an object` };
  }

  // 1. Required fields
  for (const field of REQUIRED_FIELDS) {
    if (!post[field] || typeof post[field] !== 'string' || !post[field].trim()) {
      return { valid: false, reason: `[${index}] Missing required field: ${field}` };
    }
  }

  // 2. Category slug whitelist
  if (!VALID_CATEGORY_SLUGS.has(post.category_slug)) {
    return {
      valid: false,
      reason: `[${index}] Invalid category_slug: "${post.category_slug}". Must be one of: ${[...VALID_CATEGORY_SLUGS].join(', ')}`,
    };
  }

  // 3. Post type whitelist
  if (!VALID_POST_TYPES.has(post.post_type)) {
    return {
      valid: false,
      reason: `[${index}] Invalid post_type: "${post.post_type}". Must be one of: ${[...VALID_POST_TYPES].join(', ')}`,
    };
  }

  // 4. Urgency level whitelist
  if (post.urgency_level && !VALID_URGENCY_LEVELS.has(post.urgency_level)) {
    return {
      valid: false,
      reason: `[${index}] Invalid urgency_level: "${post.urgency_level}"`,
    };
  }

  // 5. Civic status whitelist
  if (post.civic_status && !VALID_CIVIC_STATUSES.has(post.civic_status)) {
    return {
      valid: false,
      reason: `[${index}] Invalid civic_status: "${post.civic_status}"`,
    };
  }

  // 6. Slug safety — only lowercase alphanumeric and hyphens
  if (!/^[a-z0-9-]+$/.test(post.slug.trim())) {
    return {
      valid: false,
      reason: `[${index}] Slug "${post.slug}" contains invalid characters. Use only a-z, 0-9, hyphens.`,
    };
  }

  // 7. Minimum content length
  if (post.content_en.trim().length < 80) {
    return {
      valid: false,
      reason: `[${index}] content_en too short (${post.content_en.trim().length} chars). Minimum 80.`,
    };
  }

  // 8. Detect and clear garbled Tamil (Gemini JSON encoding bug).
  //    If cleared, ensureBilingualPost() will re-translate from English properly.
  const cleanTitleTa = isGarbledTamil(post.title_ta) ? '' : (post.title_ta || '').trim();
  const cleanContentTa = isGarbledTamil(post.content_ta) ? '' : (post.content_ta || '').trim();

  // 9. Enforce status = "active" and build clean DB object matching 'post' schema
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://vizhitn.in';
  const cleanSlug = post.slug.trim().toLowerCase();

  const sanitized = {
    district_slug: post.district_slug,
    category_slug: post.category_slug,
    post_type: post.post_type,
    title_en: post.title_en.trim(),
    title_ta: cleanTitleTa,
    content_en: post.content_en.trim(),
    content_ta: cleanContentTa,
    area_name: (post.area_name || '').trim(),
    assigned_department: (post.assigned_department || 'Tamil Nadu Civic Administration').trim(),
    location_text: (post.location_text || post.area_name || post.district_slug).trim(),
    urgency_level: post.urgency_level || 'medium',
    civic_status: post.civic_status || 'community_verified',
    slug: cleanSlug,
    seo_title: post.seo_title || `${post.title_en.trim()} | VizhiTN`,
    seo_description: post.seo_description || post.content_en.trim().slice(0, 155),
    seo_keywords: post.seo_keywords || `${post.district_slug} civic, ${post.category_slug}, vizhitn news`,
    canonical_url: `${siteUrl}/post/${cleanSlug}`,
    status: 'active',                    // ALWAYS override — LLM can never set "published"
    moderation_status: 'approved',
    is_publicly_visible: true,
    is_indexable: post.is_indexable ?? true,
    civic_receipt_id: post.civic_receipt_id || `TN-${Math.floor(100000 + Math.random() * 900000)}`,
    author_name: post.author_name || 'VizhiTN Civic Desk',
    upvotes: Number(post.upvotes) || Math.floor(12 + Math.random() * 28),
    verification_count: Number(post.verification_count) || Math.floor(4 + Math.random() * 9),
    created_date: new Date().toISOString(),
  };

  return { valid: true, post: sanitized };
}

/**
 * Validates a full batch of posts from an AI response.
 * Skips invalid posts and logs reasons — does not throw.
 *
 * @param {object[]} posts - Array of raw post objects.
 * @returns {{ valid: object[], skipped: { index: number, reason: string }[] }}
 */
export function validateBatch(posts) {
  if (!Array.isArray(posts)) {
    return { valid: [], skipped: [{ index: -1, reason: 'AI response is not an array' }] };
  }

  const valid = [];
  const skipped = [];

  for (let i = 0; i < posts.length; i++) {
    const result = validatePost(posts[i], i);
    if (result.valid) {
      valid.push(result.post);
    } else {
      skipped.push({ index: i, reason: result.reason });
    }
  }

  return { valid, skipped };
}
