-- Server-enforced UGC throttling and post moderation visibility.
-- Client-side limits remain useful UX, but these controls cannot be bypassed by
-- calling the Supabase REST API directly.

CREATE TABLE IF NOT EXISTS public.ugc_submission_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  action TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ugc_submission_event_lookup_idx
  ON public.ugc_submission_event (user_id, action, created_at DESC);

ALTER TABLE public.ugc_submission_event ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ugc_submission_event FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.enforce_ugc_submission_limit()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  requester UUID := auth.uid();
  requester_role TEXT := COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', 'user');
  action_name TEXT := TG_TABLE_NAME;
  max_attempts INTEGER;
  window_size INTERVAL;
  recent_attempts INTEGER;
BEGIN
  IF requester IS NULL THEN
    RAISE EXCEPTION 'Authentication is required for this submission.' USING ERRCODE = '42501';
  END IF;

  IF requester_role = 'admin' THEN
    RETURN NEW;
  END IF;

  SELECT limits.max_attempts, limits.window_size
  INTO max_attempts, window_size
  FROM (
    VALUES
      ('post',                 3, INTERVAL '10 minutes'),
      ('question',             3, INTERVAL '10 minutes'),
      ('answer',               5, INTERVAL '5 minutes'),
      ('comment',              5, INTERVAL '2 minutes'),
      ('community_discussion', 3, INTERVAL '5 minutes'),
      ('discussion_reply',     6, INTERVAL '5 minutes'),
      ('live_chat_message',    8, INTERVAL '1 minute'),
      ('live_room_message',    8, INTERVAL '1 minute'),
      ('situation_update',     3, INTERVAL '5 minutes'),
      ('emergency_post',       3, INTERVAL '10 minutes')
  ) AS limits(action, max_attempts, window_size)
  WHERE limits.action = action_name;

  IF max_attempts IS NULL THEN
    RAISE EXCEPTION 'No submission limit is configured for %.', action_name;
  END IF;

  -- Serialize attempts for this user/action so parallel requests cannot race
  -- through the count check.
  PERFORM pg_advisory_xact_lock(hashtext(requester::text || ':' || action_name));

  SELECT COUNT(*)
  INTO recent_attempts
  FROM public.ugc_submission_event
  WHERE user_id = requester
    AND action = action_name
    AND created_at >= NOW() - window_size;

  IF recent_attempts >= max_attempts THEN
    RAISE EXCEPTION 'Rate limit exceeded. Please wait before submitting again.' USING ERRCODE = 'P0001';
  END IF;

  INSERT INTO public.ugc_submission_event (user_id, action)
  VALUES (requester, action_name);

  -- New public reports require a moderation decision. Existing approved content
  -- remains visible, and administrators are exempt above.
  IF TG_TABLE_NAME = 'post' THEN
    NEW.moderation_status := 'pending';
  END IF;

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.enforce_ugc_submission_limit() FROM PUBLIC;

DO $$
DECLARE
  table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'post', 'question', 'answer', 'comment', 'community_discussion',
    'discussion_reply', 'live_chat_message', 'live_room_message',
    'situation_update', 'emergency_post'
  ]
  LOOP
    IF to_regclass('public.' || table_name) IS NOT NULL THEN
      EXECUTE format('DROP TRIGGER IF EXISTS enforce_ugc_submission_limit_trigger ON public.%I', table_name);
      EXECUTE format(
        'CREATE TRIGGER enforce_ugc_submission_limit_trigger BEFORE INSERT ON public.%I FOR EACH ROW EXECUTE FUNCTION public.enforce_ugc_submission_limit()',
        table_name
      );
    END IF;
  END LOOP;
END;
$$;

-- Anonymous visitors can read only active, approved, publicly visible reports.
-- Authors can still see their own pending submission; administrators can review all.
DROP POLICY IF EXISTS post_select ON public.post;
CREATE POLICY post_select ON public.post
FOR SELECT
USING (
  (
    status = 'active'
    AND COALESCE(moderation_status, 'approved') = 'approved'
    AND COALESCE(is_publicly_visible, true) = true
  )
  OR auth.jwt() -> 'app_metadata' ->> 'role' = 'admin'
  OR created_by_id = auth.uid()::text
);

-- Keep the limiter table bounded without requiring a scheduler extension.
CREATE OR REPLACE FUNCTION public.prune_ugc_submission_events()
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  DELETE FROM public.ugc_submission_event WHERE created_at < NOW() - INTERVAL '7 days';
$$;

REVOKE ALL ON FUNCTION public.prune_ugc_submission_events() FROM PUBLIC;
